[server]
port = 80
log_level = 1

[database]
type = "sqlite3"
url = "/app/data/node3.db"

[raft]
enabled = true
node_id = 3
nodes = [
    { id = 1, url = "http://node1" },
    { id = 2, url = "http://node2" },
    { id = 3, url = "http://node3" }
]
