[server]
port = 8083
log_level = "debug"

[database]
type = "sqlite3"
url = "node3.db"

[raft]
enabled = true
node_id = 3
nodes = [
    { id = 1, url = "http://127.0.0.1:8081" },
    { id = 2, url = "http://127.0.0.1:8082" },
    { id = 3, url = "http://127.0.0.1:8083" }
]
