apiVersion: v1
kind: Service
metadata:
  name: sso-server
  namespace: sso-system
spec:
  selector:
    app: sso-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
