/*
 * admin_page.h — Built-in admin management page HTML (auto-generated)
 */
#ifndef SSO_ADMIN_PAGE_H
#define SSO_ADMIN_PAGE_H

static const char ADMIN_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>SSO 管理后台</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    ":root{\n"
    "  --bg-dark:#0f111a;\n"
    "  --bg-card:#161925;\n"
    "  --bg-sidebar:#1a1d2c;\n"
    "  --bg-input:#1f2335;\n"
    "  --accent:#7aa2f7;\n"
    "  --accent-light:#bb9af7;\n"
    "  --accent-gradient:linear-gradient(135deg, #7aa2f7, #bb9af7);\n"
    "  --text-main:#a9b1d6;\n"
    "  --text-bright:#c0caf5;\n"
    "  --text-muted:#565f89;\n"
    "  --border:#292e42;\n"
    "  --success:#9ece6a;\n"
    "  --error:#f7768e;\n"
    "  --warning:#e0af68;\n"
    "  --radius:12px;\n"
    "  --shadow:0 10px 30px rgba(0,0,0,0.5);\n"
    "}\n"
    "body{\n"
    "  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;\n"
    "  background:var(--bg-dark);\n"
    "  color:var(--text-main);\n"
    "  min-height:100vh;\n"
    "  display:flex;\n"
    "  overflow:hidden;\n"
    "}\n"
    "/* Sidebar */\n"
    ".sidebar{\n"
    "  width:260px;\n"
    "  background:var(--bg-sidebar);\n"
    "  border-right:1px solid var(--border);\n"
    "  display:flex;\n"
    "  flex-direction:column;\n"
    "  flex-shrink:0;\n"
    "  z-index:100;\n"
    "}\n"
    ".sidebar-header{\n"
    "  padding:40px 24px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:12px;\n"
    "}\n"
    ".logo-icon{\n"
    "  width:36px;\n"
    "  height:36px;\n"
    "  background:var(--accent-gradient);\n"
    "  border-radius:10px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  color:#fff;\n"
    "  font-weight:bold;\n"
    "  font-size:20px;\n"
    "  box-shadow:0 0 20px rgba(122,162,247,0.3);\n"
    "}\n"
    ".logo-text{\n"
    "  font-size:20px;\n"
    "  font-weight:800;\n"
    "  color:var(--text-bright);\n"
    "  letter-spacing:-0.5px;\n"
    "}\n"
    ".nav-links{\n"
    "  padding:0 16px;\n"
    "  flex:1;\n"
    "}\n"
    ".nav-item{\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:12px;\n"
    "  padding:14px 16px;\n"
    "  color:var(--text-main);\n"
    "  text-decoration:none;\n"
    "  border-radius:var(--radius);\n"
    "  margin-bottom:6px;\n"
    "  transition:all 0.2s;\n"
    "  cursor:pointer;\n"
    "  font-size:14px;\n"
    "  font-weight:500;\n"
    "}\n"
    ".nav-item:hover{\n"
    "  background:rgba(255,255,255,0.04);\n"
    "  color:var(--text-bright);\n"
    "}\n"
    ".nav-item.active{\n"
    "  background:rgba(122,162,247,0.1);\n"
    "  color:var(--accent);\n"
    "}\n"
    ".sidebar-footer{\n"
    "  padding:24px;\n"
    "  border-top:1px solid var(--border);\n"
    "  background:rgba(0,0,0,0.1);\n"
    "}\n"
    ".user-profile{\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:12px;\n"
    "  margin-bottom:20px;\n"
    "}\n"
    ".user-avatar{\n"
    "  width:40px;\n"
    "  height:40px;\n"
    "  background:var(--bg-input);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:12px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  color:var(--accent);\n"
    "  font-weight:bold;\n"
    "}\n"
    ".user-meta{\n"
    "  flex:1;\n"
    "  min-width:0;\n"
    "}\n"
    ".user-name{\n"
    "  font-size:14px;\n"
    "  font-weight:600;\n"
    "  color:var(--text-bright);\n"
    "  white-space:nowrap;\n"
    "  overflow:hidden;\n"
    "  text-overflow:ellipsis;\n"
    "}\n"
    ".user-role{\n"
    "  font-size:11px;\n"
    "  color:var(--text-muted);\n"
    "  text-transform:uppercase;\n"
    "  letter-spacing:0.5px;\n"
    "}\n"
    "/* Main Content */\n"
    ".main{\n"
    "  flex:1;\n"
    "  display:flex;\n"
    "  flex-direction:column;\n"
    "  overflow:hidden;\n"
    "  position:relative;\n"
    "}\n"
    ".top-bar{\n"
    "  height:72px;\n"
    "  padding:0 40px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:space-between;\n"
    "  border-bottom:1px solid var(--border);\n"
    "  background:rgba(15, 17, 26, 0.7);\n"
    "  backdrop-filter:blur(20px);\n"
    "}\n"
    ".page-title{\n"
    "  font-size:22px;\n"
    "  font-weight:700;\n"
    "  color:var(--text-bright);\n"
    "  letter-spacing:-0.5px;\n"
    "}\n"
    ".content-area{\n"
    "  flex:1;\n"
    "  padding:40px;\n"
    "  overflow-y:auto;\n"
    "}\n"
    ".grid{\n"
    "  display:grid;\n"
    "  grid-template-columns:repeat(auto-fill, minmax(280px, 1fr));\n"
    "  gap:24px;\n"
    "  margin-bottom:40px;\n"
    "}\n"
    "/* Stats Card */\n"
    ".stat-card{\n"
    "  background:var(--bg-card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:16px;\n"
    "  padding:24px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:20px;\n"
    "  transition:transform 0.2s;\n"
    "}\n"
    ".stat-card:hover{transform:translateY(-2px)}\n"
    ".stat-icon{\n"
    "  width:56px;\n"
    "  height:56px;\n"
    "  border-radius:14px;\n"
    "  background:var(--bg-input);\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  font-size:24px;\n"
    "  color:var(--accent);\n"
    "}\n"
    ".stat-info .stat-label{\n"
    "  font-size:12px;\n"
    "  color:var(--text-muted);\n"
    "  font-weight:600;\n"
    "  text-transform:uppercase;\n"
    "  letter-spacing:1px;\n"
    "  margin-bottom:6px;\n"
    "}\n"
    ".stat-info .stat-value{\n"
    "  font-size:28px;\n"
    "  font-weight:800;\n"
    "  color:var(--text-bright);\n"
    "}\n"
    "/* Table Card */\n"
    ".card{\n"
    "  background:var(--bg-card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:16px;\n"
    "  overflow:hidden;\n"
    "  box-shadow:var(--shadow);\n"
    "}\n"
    ".card-header{\n"
    "  padding:24px 32px;\n"
    "  border-bottom:1px solid var(--border);\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:space-between;\n"
    "}\n"
    ".card-title{\n"
    "  font-size:18px;\n"
    "  font-weight:700;\n"
    "  color:var(--text-bright);\n"
    "}\n"
    ".table-wrapper{\n"
    "  overflow-x:auto;\n"
    "}\n"
    "table{\n"
    "  width:100%;\n"
    "  border-collapse:collapse;\n"
    "}\n"
    "th{\n"
    "  background:rgba(0,0,0,0.15);\n"
    "  padding:14px 32px;\n"
    "  text-align:left;\n"
    "  font-size:12px;\n"
    "  text-transform:uppercase;\n"
    "  color:var(--text-muted);\n"
    "  font-weight:700;\n"
    "  letter-spacing:1px;\n"
    "}\n"
    "td{\n"
    "  padding:18px 32px;\n"
    "  border-bottom:1px solid var(--border);\n"
    "  font-size:14px;\n"
    "  color:var(--text-main);\n"
    "}\n"
    "tr:last-child td{border-bottom:none}\n"
    "tr:hover td{background:rgba(255,255,255,0.015)}\n"
    "/* Components */\n"
    ".btn{\n"
    "  display:inline-flex;\n"
    "  align-items:center;\n"
    "  gap:8px;\n"
    "  padding:10px 20px;\n"
    "  border-radius:var(--radius);\n"
    "  font-size:14px;\n"
    "  font-weight:600;\n"
    "  cursor:pointer;\n"
    "  transition:all 0.2s;\n"
    "  border:none;\n"
    "  outline:none;\n"
    "}\n"
    ".btn-primary{\n"
    "  background:var(--accent-gradient);\n"
    "  color:#fff;\n"
    "  box-shadow:0 4px 15px rgba(122,162,247,0.3);\n"
    "}\n"
    ".btn-primary:hover{opacity:0.9;transform:translateY(-1px);box-shadow:0 6px 20px rgba(122,162,247,0.4)}\n"
    ".btn-outline{\n"
    "  background:rgba(255,255,255,0.03);\n"
    "  border:1px solid var(--border);\n"
    "  color:var(--text-bright);\n"
    "}\n"
    ".btn-outline:hover{background:var(--bg-input);border-color:var(--text-muted)}\n"
    ".btn-danger{\n"
    "  background:rgba(247,118,142,0.1);\n"
    "  color:var(--error);\n"
    "  border:1px solid rgba(247,118,142,0.2);\n"
    "}\n"
    ".btn-danger:hover{background:var(--error);color:#fff}\n"
    ".btn-sm{padding:6px 12px;font-size:12px;border-radius:6px}\n"
    "\n"
    ".status-pill{\n"
    "  display:inline-flex;\n"
    "  align-items:center;\n"
    "  gap:6px;\n"
    "  font-size:12px;\n"
    "  font-weight:600;\n"
    "  padding:4px 12px;\n"
    "  border-radius:20px;\n"
    "}\n"
    ".status-active{background:rgba(158,206,106,0.1);color:var(--success)}\n"
    ".status-inactive{background:rgba(247,118,142,0.1);color:var(--error)}\n"
    "\n"
    ".tag{\n"
    "  padding:2px 8px;\n"
    "  border-radius:4px;\n"
    "  font-size:11px;\n"
    "  font-weight:600;\n"
    "  background:rgba(122,162,247,0.1);\n"
    "  color:var(--accent);\n"
    "}\n"
    "\n"
    "/* Modal */\n"
    ".modal-overlay{\n"
    "  position:fixed;\n"
    "  inset:0;\n"
    "  background:rgba(0,0,0,0.8);\n"
    "  backdrop-filter:blur(8px);\n"
    "  display:none;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  z-index:1000;\n"
    "  animation:fadeIn 0.2s;\n"
    "}\n"
    "@keyframes fadeIn{from{opacity:0}to{opacity:1}}\n"
    ".modal-overlay.active{display:flex}\n"
    ".modal{\n"
    "  background:var(--bg-card);\n"
    "  border:1px solid var(--border);\n"
    "  width:540px;\n"
    "  max-width:95%;\n"
    "  border-radius:20px;\n"
    "  padding:40px;\n"
    "  box-shadow:0 30px 60px rgba(0,0,0,0.6);\n"
    "}\n"
    ".modal h3{font-size:22px;color:var(--text-bright);font-weight:700;margin-bottom:8px}\n"
    ".modal p{font-size:14px;color:var(--text-muted);margin-bottom:24px}\n"
    ".form-group{margin-bottom:24px}\n"
    ".form-group label{display:block;font-size:13px;font-weight:600;color:var(--text-muted);margin-bottom:10px;text-transform:uppercase;letter-spacing:0.5px}\n"
    "input, select, textarea{\n"
    "  width:100%;\n"
    "  background:var(--bg-input);\n"
    "  border:1px solid var(--border);\n"
    "  padding:14px 18px;\n"
    "  border-radius:var(--radius);\n"
    "  color:var(--text-bright);\n"
    "  font-size:15px;\n"
    "  outline:none;\n"
    "  transition:all 0.2s;\n"
    "}\n"
    "input:focus{border-color:var(--accent);box-shadow:0 0 0 4px rgba(122,162,247,0.15)}\n"
    ".modal-footer{\n"
    "  display:flex;\n"
    "  justify-content:flex-end;\n"
    "  gap:12px;\n"
    "  margin-top:40px;\n"
    "}\n"
    "/* Scrollbar */\n"
    "::-webkit-scrollbar{width:8px}\n"
    "::-webkit-scrollbar-track{background:transparent}\n"
    "::-webkit-scrollbar-thumb{background:var(--border);border-radius:10px}\n"
    "::-webkit-scrollbar-thumb:hover{background:var(--text-muted)}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div class=\"sidebar\">\n"
    "  <div class=\"sidebar-header\">\n"
    "    <div class=\"logo-icon\">S</div>\n"
    "    <div class=\"logo-text\">SSO Admin</div>\n"
    "  </div>\n"
    "  <div class=\"nav-links\">\n"
    "    <div class=\"nav-item active\" onclick=\"switchTab('users', this)\"><span>👥</span> 用户管理</div>\n"
    "    <div class=\"nav-item\" onclick=\"switchTab('roles', this)\"><span>🔐</span> 角色权限</div>\n"
    "    <div class=\"nav-item\" onclick=\"switchTab('groups', this)\"><span>🏢</span> 组织架构</div>\n"
    "    <div class=\"nav-item\" onclick=\"switchTab('policies', this)\"><span>📜</span> 策略配置</div>\n"
    "    <div class=\"nav-item\" onclick=\"switchTab('metrics', this)\"><span>📊</span> 系统指标</div>\n"
    "  </div>\n"
    "  <div class=\"sidebar-footer\">\n"
    "    <div class=\"user-profile\">\n"
    "      <div class=\"user-avatar\" id=\"avatar\">A</div>\n"
    "      <div class=\"user-meta\">\n"
    "        <div class=\"user-name\" id=\"adminName\">Administrator</div>\n"
    "        <div class=\"user-role\">Super Admin</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <button class=\"btn btn-outline\" style=\"width:100%;justify-content:center\" onclick=\"logout()\">退出登录</button>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div class=\"main\">\n"
    "  <div class=\"top-bar\">\n"
    "    <div class=\"page-title\" id=\"pageTitle\">用户管理</div>\n"
    "    <div class=\"top-actions\">\n"
    "      <button class=\"btn btn-primary\" id=\"addBtn\" onclick=\"handleAdd()\">+ 新增用户</button>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"content-area\">\n"
    "    <!-- Stats Row -->\n"
    "    <div class=\"grid\">\n"
    "      <div class=\"stat-card\">\n"
    "        <div class=\"stat-icon\" style=\"color:#7aa2f7;background:rgba(122,162,247,0.1)\">👥</div>\n"
    "        <div class=\"stat-info\">\n"
    "          <div class=\"stat-label\">总用户数</div>\n"
    "          <div class=\"stat-value\" id=\"countUsers\">0</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"stat-card\">\n"
    "        <div class=\"stat-icon\" style=\"color:#bb9af7;background:rgba(187,154,247,0.1)\">🛡️</div>\n"
    "        <div class=\"stat-info\">\n"
    "          <div class=\"stat-label\">活跃策略</div>\n"
    "          <div class=\"stat-value\" id=\"countPolicies\">0</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"stat-card\">\n"
    "        <div class=\"stat-icon\" style=\"color:#9ece6a;background:rgba(158,206,106,0.1)\">⚡</div>\n"
    "        <div class=\"stat-info\">\n"
    "          <div class=\"stat-label\">鉴权 QPS</div>\n"
    "          <div class=\"stat-value\" id=\"avgQps\">0.0</div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- Data Table -->\n"
    "    <div class=\"card\">\n"
    "      <div class=\"card-header\">\n"
    "        <div class=\"card-title\">数据概览</div>\n"
    "        <div style=\"font-size:12px;color:var(--text-muted)\">实时同步中</div>\n"
    "      </div>\n"
    "      <div class=\"table-wrapper\" id=\"tableContainer\">\n"
    "        <div style=\"padding:60px;text-align:center;color:var(--text-muted)\">正在加载核心组件数据...</div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- Modal -->\n"
    "<div class=\"modal-overlay\" id=\"modalOverlay\">\n"
    "  <div class=\"modal\">\n"
    "    <h3 id=\"modalTitle\">新增用户</h3>\n"
    "    <p id=\"modalSub\">请填写下方表单完成操作</p>\n"
    "    <div id=\"modalContent\"></div>\n"
    "    <div class=\"modal-footer\">\n"
    "      <button class=\"btn btn-outline\" onclick=\"closeModal()\">取消</button>\n"
    "      <button class=\"btn btn-primary\" id=\"confirmBtn\" onclick=\"confirmAdd()\">保存提交</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "let currentTab = 'users';\n"
    "const TOKEN_KEY = 'sso_token';\n"
    "\n"
    "function switchTab(tab, el) {\n"
    "  currentTab = tab;\n"
    "  document.querySelectorAll('.nav-item').forEach(i => i.classList.remove('active'));\n"
    "  el.classList.add('active');\n"
    "  document.getElementById('pageTitle').textContent = el.textContent.trim().substring(2);\n"
    "  document.getElementById('addBtn').textContent = '+ 新增' + el.textContent.trim().substring(2);\n"
    "  document.getElementById('addBtn').style.display = tab === 'metrics' ? 'none' : 'flex';\n"
    "  loadData();\n"
    "}\n"
    "\n"
    "async function api(path, method='GET', body=null) {\n"
    "  const token = localStorage.getItem(TOKEN_KEY);\n"
    "  const headers = {'Content-Type':'application/json'};\n"
    "  if(token) headers['Authorization'] = 'Bearer ' + token;\n"
    "  const r = await fetch(path, {method, headers, body: body ? JSON.stringify(body) : null});\n"
    "  if(r.status === 401) { logout(); return; }\n"
    "  return r.json();\n"
    "}\n"
    "\n"
    "function loadData() {\n"
    "  const container = document.getElementById('tableContainer');\n"
    "  if(currentTab === 'users') {\n"
    "    api('/api/v1/users').then(users => {\n"
    "      document.getElementById('countUsers').textContent = users.length;\n"
    "      let html = '<table><thead><tr><th>ID</th><th>用户名</th><th>邮箱</th><th>手机号</th><th>状态</th><th>操作</th></tr></thead><tbody>';\n"
    "      users.forEach(u => {\n"
    "        html += `<tr>\n"
    "          <td>#${u.id}</td>\n"
    "          <td style=\"color:var(--text-bright);font-weight:600\">${u.username}</td>\n"
    "          <td>${u.email || '-'}</td>\n"
    "          <td>${u.phone || '-'}</td>\n"
    "          <td><span class=\"status-pill ${u.status === 1 ? 'status-active' : 'status-inactive'}\">${u.status === 1 ? '● 正常' : '● 禁用'}</span></td>\n"
    "          <td>\n"
    "            <button class=\"btn btn-outline btn-sm\" onclick=\"editUser(${u.id})\">管理</button>\n"
    "          </td>\n"
    "        </tr>`;\n"
    "      });\n"
    "      container.innerHTML = html + '</tbody></table>';\n"
    "    });\n"
    "  } else if(currentTab === 'policies') {\n"
    "    api('/api/v1/policies').then(policies => {\n"
    "      document.getElementById('countPolicies').textContent = policies.length;\n"
    "      let html = '<table><thead><tr><th>ID</th><th>策略名称</th><th>类型</th><th>效果</th><th>操作</th></tr></thead><tbody>';\n"
    "      policies.forEach(p => {\n"
    "        html += `<tr>\n"
    "          <td>#${p.id}</td>\n"
    "          <td style=\"color:var(--text-bright);font-weight:600\">${p.name}</td>\n"
    "          <td><span class=\"tag\">${p.strategy_type}</span></td>\n"
    "          <td><span style=\"color:${p.effect === 1 ? 'var(--success)' : 'var(--error)'};font-weight:700\">${p.effect === 1 ? 'ALLOW' : 'DENY'}</span></td>\n"
    "          <td><button class=\"btn btn-outline btn-sm\">配置</button></td>\n"
    "        </tr>`;\n"
    "      });\n"
    "      container.innerHTML = html + '</tbody></table>';\n"
    "    });\n"
    "  } else if(currentTab === 'metrics') {\n"
    "    fetch('/metrics').then(r => r.text()).then(m => {\n"
    "      container.innerHTML = `<pre style=\"padding:32px;background:var(--bg-dark);color:#79dac8;font-family:monospace;font-size:13px;line-height:1.5\">${m}</pre>`;\n"
    "    });\n"
    "  }\n"
    "}\n"
    "\n"
    "function logout() { localStorage.removeItem(TOKEN_KEY); window.location.href = '/login'; }\n"
    "function closeModal() { document.getElementById('modalOverlay').classList.remove('active'); }\n"
    "function showModal(title, sub) { \n"
    "  document.getElementById('modalTitle').textContent = title;\n"
    "  document.getElementById('modalSub').textContent = sub;\n"
    "  document.getElementById('modalOverlay').classList.add('active'); \n"
    "}\n"
    "\n"
    "function handleAdd() {\n"
    "  showModal('新增' + document.getElementById('pageTitle').textContent, '请填写基础信息以创建新资源');\n"
    "  const content = document.getElementById('modalContent');\n"
    "  if(currentTab === 'users') {\n"
    "    content.innerHTML = `\n"
    "      <div class=\"form-group\"><label>用户名</label><input id=\"new_user\" placeholder=\"必填\"></div>\n"
    "      <div class=\"form-group\"><label>密码</label><input type=\"password\" id=\"new_pass\" placeholder=\"必填\"></div>\n"
    "      <div class=\"form-group\"><label>手机号</label><input id=\"new_phone\" placeholder=\"可选\"></div>\n"
    "    `;\n"
    "  }\n"
    "}\n"
    "\n"
    "async function confirmAdd() {\n"
    "  if(currentTab === 'users') {\n"
    "    const user = {\n"
    "      username: document.getElementById('new_user').value,\n"
    "      password: document.getElementById('new_pass').value,\n"
    "      phone: document.getElementById('new_phone').value\n"
    "    };\n"
    "    await api('/api/v1/users', 'POST', user);\n"
    "    closeModal();\n"
    "    loadData();\n"
    "  }\n"
    "}\n"
    "\n"
    "// Initial\n"
    "const token = localStorage.getItem(TOKEN_KEY) || (window.location.hash.length > 1 ? decodeURIComponent(window.location.hash.substring(1)) : null);\n"
    "if(token) {\n"
    "  localStorage.setItem(TOKEN_KEY, token);\n"
    "  window.location.hash = '';\n"
    "  api('/api/v1/auth/me').then(d => {\n"
    "    if(d && d.username) {\n"
    "      document.getElementById('adminName').textContent = d.display_name || d.username;\n"
    "      document.getElementById('avatar').textContent = (d.display_name || d.username)[0].toUpperCase();\n"
    "    }\n"
    "  }).catch(() => { /* handled by api() */ });\n"
    "  loadData();\n"
    "} else {\n"
    "  window.location.href = '/login';\n"
    "}\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;

#endif /* SSO_ADMIN_PAGE_H */
