/*
 * admin_page.h — Built-in admin management page HTML (auto-generated)
 */
#ifndef SSO_ADMIN_PAGE_H
#define SSO_ADMIN_PAGE_H

static const char ADMIN_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\\\"zh-CN\\\">\n"
    "<head>\n"
    "<meta charset=\\\"utf-8\\\">\n"
    "<meta name=\\\"viewport\\\" content=\\\"width=device-width, initial-scale=1\\\">\n"
    "<meta http-equiv=\\\"Cache-Control\\\" content=\\\"no-cache, no-store, must-revalidate\\\">\n"
    "<meta http-equiv=\\\"Pragma\\\" content=\\\"no-cache\\\">\n"
    "<title>SSO 权限管理</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,sans-serif;background:linear-gradient(135deg,#0f0c29,#302b63,#24243e);color:#e0e0e0;min-height:100vh;display:flex}\n"
    ":root{--accent:#6c63ff;--accent-hover:#5a52d5;--danger:#ff4757;--success:#2ed573;--warning:#ffa502;--bg-card:rgba(255,255,255,0.06);--bg-hover:rgba(255,255,255,0.1);--border:rgba(255,255,255,0.12)}\n"
    ".sidebar{width:220px;background:rgba(0,0,0,0.3);backdrop-filter:blur(12px);padding:24px 0;border-right:1px solid var(--border);flex-shrink:0;display:flex;flex-direction:column;overflow-y:auto;position:sticky;top:0;height:100vh}\n"
    ".sidebar .logo{padding:0 20px 24px;font-size:20px;font-weight:700;background:linear-gradient(135deg,var(--accent),#e0e0e0);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}\n"
    ".sidebar .user-info{padding:8px 20px 16px;font-size:13px;color:#999;border-bottom:1px solid var(--border);margin-bottom:8px;word-break:break-all}\n"
    ".sidebar nav a{display:flex;align-items:center;gap:10px;padding:10px 20px;font-size:14px;color:#ccc;transition:all .2s;cursor:pointer;border:none;background:none;width:100%;text-align:left}\n"
    ".sidebar nav a:hover{background:var(--bg-hover);color:#fff}\n"
    ".sidebar nav a.active{background:var(--bg-card);color:var(--accent);border-right:3px solid var(--accent)}\n"
    ".sidebar .logout-btn{margin-top:auto;padding:12px 20px;font-size:13px;color:#999;cursor:pointer;background:none;border:none;border-top:1px solid var(--border);text-align:left;transition:color .2s;width:100%}\n"
    ".sidebar .logout-btn:hover{color:var(--danger)}\n"
    ".main{flex:1;padding:32px;overflow-y:auto;max-height:100vh}\n"
    ".section{display:none}\n"
    ".section.active{display:block}\n"
    ".section h2{font-size:22px;font-weight:600;margin-bottom:20px;background:linear-gradient(135deg,var(--accent),#e0e0e0);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}\n"
    ".card{background:var(--bg-card);backdrop-filter:blur(12px);border-radius:12px;padding:20px;margin-bottom:20px;border:1px solid var(--border)}\n"
    ".card h3{font-size:16px;font-weight:600;margin-bottom:14px;color:#fff}\n"
    ".card-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;flex-wrap:wrap;gap:8px}\n"
    ".card-header h3{margin-bottom:0}\n"
    "table{width:100%;border-collapse:collapse;font-size:14px}\n"
    "th{text-align:left;padding:10px 12px;color:#999;font-weight:500;border-bottom:1px solid var(--border);font-size:12px;text-transform:uppercase;white-space:nowrap}\n"
    "td{padding:10px 12px;border-bottom:1px solid rgba(255,255,255,0.06)}\n"
    "tr:hover td{background:var(--bg-hover)}\n"
    ".btn{display:inline-flex;align-items:center;gap:6px;padding:8px 18px;border-radius:6px;font-size:13px;font-weight:500;cursor:pointer;border:none;transition:all .2s;font-family:inherit}\n"
    ".btn-primary{background:var(--accent);color:#fff}\n"
    ".btn-primary:hover{background:var(--accent-hover)}\n"
    ".btn-sm{padding:4px 10px;font-size:12px}\n"
    ".btn-danger{background:var(--danger);color:#fff}\n"
    ".btn-danger:hover{background:#e0404f}\n"
    ".btn-success{background:var(--success);color:#fff}\n"
    ".btn-success:hover{background:#26bf62}\n"
    ".btn-outline{background:transparent;border:1px solid var(--border);color:#ccc}\n"
    ".btn-outline:hover{background:var(--bg-hover);color:#fff}\n"
    "input,select,textarea{width:100%;padding:10px 12px;border-radius:6px;border:1px solid var(--border);background:rgba(255,255,255,0.08);color:#e0e0e0;font-size:14px;font-family:inherit;transition:border .2s}\n"
    "input:focus,select:focus,textarea:focus{outline:none;border-color:var(--accent)}\n"
    "input::placeholder{color:#666}\n"
    "select option{background:#302b63;color:#e0e0e0}\n"
    "textarea{resize:vertical;min-height:80px;font-family:monospace;font-size:13px}\n"
    ".form-row{display:flex;gap:12px;margin-bottom:12px;flex-wrap:wrap}\n"
    ".form-row>*{flex:1;min-width:180px}\n"
    ".form-group{margin-bottom:12px}\n"
    ".form-group label{display:block;font-size:13px;color:#999;margin-bottom:4px}\n"
    ".tag{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;margin:1px;background:var(--accent);color:#fff;white-space:nowrap}\n"
    ".tag-success{background:var(--success)}\n"
    ".tag-danger{background:var(--danger)}\n"
    ".tag-warning{background:var(--warning)}\n"
    ".status-badge{display:inline-block;padding:2px 10px;border-radius:10px;font-size:11px;font-weight:500}\n"
    ".status-active{background:rgba(46,213,115,0.2);color:var(--success)}\n"
    ".status-inactive{background:rgba(255,165,2,0.2);color:var(--warning)}\n"
    ".status-disabled{background:rgba(255,71,87,0.2);color:var(--danger)}\n"
    ".modal-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,0.6);backdrop-filter:blur(4px);z-index:1000;justify-content:center;align-items:center}\n"
    ".modal-overlay.active{display:flex}\n"
    ".modal{background:#2a2744;border-radius:12px;padding:24px;width:90%;max-width:560px;max-height:80vh;overflow-y:auto;border:1px solid var(--border);box-shadow:0 20px 40px rgba(0,0,0,0.4)}\n"
    ".modal h3{font-size:18px;margin-bottom:16px;color:#fff}\n"
    ".modal .btn-row{display:flex;gap:8px;justify-content:flex-end;margin-top:16px}\n"
    ".toast-container{position:fixed;top:20px;right:20px;z-index:2000;display:flex;flex-direction:column;gap:8px;pointer-events:none}\n"
    ".toast{padding:12px 20px;border-radius:8px;font-size:14px;color:#fff;box-shadow:0 4px 12px rgba(0,0,0,0.3);animation:slideIn .3s ease-out;pointer-events:auto}\n"
    "@keyframes slideIn{from{transform:translateX(100%);opacity:0}to{transform:translateX(0);opacity:1}}\n"
    ".toast-success{background:linear-gradient(135deg,var(--success),#26bf62)}\n"
    ".toast-error{background:linear-gradient(135deg,var(--danger),#e0404f)}\n"
    ".empty-state{text-align:center;padding:40px 20px;color:#666;font-size:14px}\n"
    ".loading{text-align:center;padding:20px;color:#999}\n"
    ".badge-count{display:inline-flex;align-items:center;justify-content:center;min-width:20px;height:20px;border-radius:10px;background:var(--accent);color:#fff;font-size:11px;font-weight:600;margin-left:6px}\n"
    ".search-bar{margin-bottom:12px}\n"
    ".search-bar input{max-width:320px}\n"
    ".detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}\n"
    ".detail-grid .label{color:#999;font-size:13px}\n"
    ".detail-grid .value{font-size:14px;margin-bottom:8px}\n"
    "@media(max-width:768px){.sidebar{width:60px}.sidebar .logo,.sidebar .user-info,.sidebar nav a span:last-child{display:none}.sidebar nav a{justify-content:center;padding:12px}.main{padding:16px}.form-row>*{flex:1 1 100%}.modal{width:95%;padding:16px}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div class=\\\"sidebar\\\">\n"
    "<div class=\\\"logo\\\">SSO 管理</div>\n"
    "<div class=\\\"user-info\\\" id=\\\"userInfo\\\">未登录</div>\n"
    "<nav>\n"
    "<a class=\\\"active\\\" data-section=\\\"users\\\" onclick=\\\"switchSection('users')\\\"><span>👥</span><span>用户管理</span></a>\n"
    "<a data-section=\\\"roles\\\" onclick=\\\"switchSection('roles')\\\"><span>🔑</span><span>角色管理</span></a>\n"
    "<a data-section=\\\"policies\\\" onclick=\\\"switchSection('policies')\\\"><span>📋</span><span>策略管理</span></a>\n"
    "<a data-section=\\\"groups\\\" onclick=\\\"switchSection('groups')\\\"><span>🏛</span><span>分组管理</span></a>\n"
    "</nav>\n"
    "<button class=\\\"logout-btn\\\" onclick=\\\"logout()\\\">🚪 退出登录</button>\n"
    "</div>\n"
    "\n"
    "<div class=\\\"main\\\">\n"
    "<div class=\\\"section active\\\" id=\\\"section-users\\\">\n"
    "<h2>用户管理</h2>\n"
    "<div class=\\\"card\\\">\n"
    "<div class=\\\"card-header\\\">\n"
    "<h3>用户列表 <span class=\\\"badge-count\\\" id=\\\"userCount\\\">0</span></h3>\n"
    "<div style=\\\"display:flex;gap:8px;flex-wrap:wrap\\\">\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"showCreateUserModal()\\\">+ 创建用户</button>\n"
    "</div>\n"
    "</div>\n"
    "<div class=\\\"search-bar\\\"><input type=\\\"text\\\" id=\\\"userSearch\\\" placeholder=\\\"搜索用户...\\\" oninput=\\\"filterUsers()\\\"></div>\n"
    "<div id=\\\"userList\\\"><div class=\\\"loading\\\">加载中...</div></div>\n"
    "</div></div>\n"
    "\n"
    "<div class=\\\"section\\\" id=\\\"section-roles\\\">\n"
    "<h2>角色管理</h2>\n"
    "<div class=\\\"card\\\">\n"
    "<div class=\\\"card-header\\\">\n"
    "<h3>角色列表 <span class=\\\"badge-count\\\" id=\\\"roleCount\\\">0</span></h3>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"showCreateRoleModal()\\\">+ 创建角色</button>\n"
    "</div>\n"
    "<div id=\\\"roleList\\\"><div class=\\\"loading\\\">加载中...</div></div>\n"
    "</div></div>\n"
    "\n"
    "<div class=\\\"section\\\" id=\\\"section-policies\\\">\n"
    "<h2>策略管理</h2>\n"
    "<div class=\\\"card\\\">\n"
    "<div class=\\\"card-header\\\">\n"
    "<h3>权限策略列表 <span class=\\\"badge-count\\\" id=\\\"policyCount\\\">0</span></h3>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"showCreatePolicyModal()\\\">+ 创建策略</button>\n"
    "</div>\n"
    "<div id=\\\"policyList\\\"><div class=\\\"loading\\\">加载中...</div></div>\n"
    "</div></div>\n"
    "\n"
    "<div class=\\\"section\\\" id=\\\"section-groups\\\">\n"
    "<h2>分组管理</h2>\n"
    "<div class=\\\"card\\\">\n"
    "<div class=\\\"card-header\\\">\n"
    "<h3>分组列表 <span class=\\\"badge-count\\\" id=\\\"groupCount\\\">0</span></h3>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"showCreateGroupModal()\\\">+ 创建分组</button>\n"
    "</div>\n"
    "<div id=\\\"groupList\\\"><div class=\\\"loading\\\">加载中...</div></div>\n"
    "</div></div>\n"
    "</div>\n"
    "\n"
    "<div class=\\\"toast-container\\\" id=\\\"toastContainer\\\"></div>\n"
    "\n"
    "<div class=\\\"modal-overlay\\\" id=\\\"createUserModal\\\"><div class=\\\"modal\\\">\n"
    "<h3>创建用户</h3>\n"
    "<div class=\\\"form-group\\\"><label>用户名</label><input id=\\\"cuUsername\\\" placeholder=\\\"username\\\"></div>\n"
    "<div class=\\\"form-row\\\">\n"
    "<div class=\\\"form-group\\\"><label>密码</label><input id=\\\"cuPassword\\\" type=\\\"password\\\"></div>\n"
    "<div class=\\\"form-group\\\"><label>邮箱</label><input id=\\\"cuEmail\\\" placeholder=\\\"user@example.com\\\"></div>\n"
    "</div>\n"
    "<div class=\\\"form-group\\\"><label>显示名称</label><input id=\\\"cuDisplay\\\" placeholder=\\\"显示名称\\\"></div>\n"
    "<div class=\\\"btn-row\\\">\n"
    "<button class=\\\"btn btn-outline\\\" onclick=\\\"closeModal('createUserModal')\\\">取消</button>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"createUser()\\\">创建</button>\n"
    "</div></div></div>\n"
    "\n"
    "<div class=\\\"modal-overlay\\\" id=\\\"assignRoleModal\\\"><div class=\\\"modal\\\">\n"
    "<h3>分配角色</h3>\n"
    "<p style=\\\"margin-bottom:12px;color:#999;font-size:14px\\\" id=\\\"assignRoleUser\\\"></p>\n"
    "<div class=\\\"form-group\\\"><label>选择角色</label><select id=\\\"assignRoleSelect\\\"></select></div>\n"
    "<div class=\\\"btn-row\\\">\n"
    "<button class=\\\"btn btn-outline\\\" onclick=\\\"closeModal('assignRoleModal')\\\">取消</button>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"assignRole()\\\">分配</button>\n"
    "</div></div></div>\n"
    "\n"
    "<div class=\\\"modal-overlay\\\" id=\\\"createRoleModal\\\"><div class=\\\"modal\\\">\n"
    "<h3>创建角色</h3>\n"
    "<div class=\\\"form-group\\\"><label>角色名称</label><input id=\\\"crName\\\" placeholder=\\\"角色名\\\"></div>\n"
    "<div class=\\\"form-group\\\"><label>描述</label><input id=\\\"crDesc\\\" placeholder=\\\"角色描述\\\"></div>\n"
    "<div class=\\\"form-group\\\"><label>父角色</label><select id=\\\"crParent\\\"><option value=\\\"0\\\">无（顶级角色）</option></select></div>\n"
    "<div class=\\\"btn-row\\\">\n"
    "<button class=\\\"btn btn-outline\\\" onclick=\\\"closeModal('createRoleModal')\\\">取消</button>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"createRole()\\\">创建</button>\n"
    "</div></div></div>\n"
    "\n"
    "<div class=\\\"modal-overlay\\\" id=\\\"createPolicyModal\\\"><div class=\\\"modal\\\">\n"
    "<h3>创建策略</h3>\n"
    "<div class=\\\"form-group\\\"><label>策略名称</label><input id=\\\"cpName\\\" placeholder=\\\"策略名\\\"></div>\n"
    "<div class=\\\"form-row\\\">\n"
    "<div class=\\\"form-group\\\"><label>策略类型</label><select id=\\\"cpStrategy\\\">\n"
    "<option value=\\\"1\\\">FUNCTIONAL</option>\n"
    "<option value=\\\"2\\\">API</option>\n"
    "<option value=\\\"3\\\">DATA</option></select></div>\n"
    "<div class=\\\"form-group\\\"><label>效果</label><select id=\\\"cpEffect\\\">\n"
    "<option value=\\\"1\\\">ALLOW</option>\n"
    "<option value=\\\"2\\\">DENY</option></select></div>\n"
    "<div class=\\\"form-group\\\"><label>优先级</label><input id=\\\"cpPriority\\\" type=\\\"number\\\" value=\\\"50\\\"></div>\n"
    "</div>\n"
    "<div class=\\\"form-group\\\"><label>规则 JSON</label><textarea id=\\\"cpRules\\\" placeholder='{\\\"functions\\\":[{\\\"code\\\":\\\"admin:*\\\",\\\"effect\\\":\\\"allow\\\"}]}'></textarea></div>\n"
    "<div class=\\\"btn-row\\\">\n"
    "<button class=\\\"btn btn-outline\\\" onclick=\\\"closeModal('createPolicyModal')\\\">取消</button>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"createPolicy()\\\">创建</button>\n"
    "</div></div></div>\n"
    "\n"
    "<div class=\\\"modal-overlay\\\" id=\\\"assignPolicyModal\\\"><div class=\\\"modal\\\">\n"
    "<h3>分配策略</h3>\n"
    "<p style=\\\"margin-bottom:12px;color:#999;font-size:14px\\\" id=\\\"assignPolicyInfo\\\"></p>\n"
    "<div class=\\\"form-group\\\"><label>目标类型</label>\n"
    "<select id=\\\"apTargetType\\\"><option value=\\\"1\\\">角色 (Role)</option><option value=\\\"2\\\">用户 (User)</option><option value=\\\"3\\\">分组 (Group)</option></select></div>\n"
    "<div class=\\\"form-group\\\"><label>目标 ID</label><input id=\\\"apTargetId\\\" type=\\\"number\\\" placeholder=\\\"输入目标 ID\\\"></div>\n"
    "<div class=\\\"btn-row\\\">\n"
    "<button class=\\\"btn btn-outline\\\" onclick=\\\"closeModal('assignPolicyModal')\\\">取消</button>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"assignPolicy()\\\">分配</button>\n"
    "</div></div></div>\n"
    "\n"
    "<div class=\\\"modal-overlay\\\" id=\\\"createGroupModal\\\"><div class=\\\"modal\\\">\n"
    "<h3>创建分组</h3>\n"
    "<div class=\\\"form-group\\\"><label>分组名称</label><input id=\\\"cgName\\\" placeholder=\\\"分组名\\\"></div>\n"
    "<div class=\\\"form-group\\\"><label>描述</label><input id=\\\"cgDesc\\\" placeholder=\\\"分组描述\\\"></div>\n"
    "<div class=\\\"form-group\\\"><label>父分组</label><select id=\\\"cgParent\\\"><option value=\\\"0\\\">无（顶级分组）</option></select></div>\n"
    "<div class=\\\"btn-row\\\">\n"
    "<button class=\\\"btn btn-outline\\\" onclick=\\\"closeModal('createGroupModal')\\\">取消</button>\n"
    "<button class=\\\"btn btn-primary\\\" onclick=\\\"createGroup()\\\">创建</button>\n"
    "</div></div></div>\n"
    "\n"
    "<script>\n"
    "// State\n"
    "const TOKEN_KEY = 'sso_token';\n"
    "const API_BASE = '';\n"
    "\n"
    "function getToken() {\n"
    "  var t = localStorage.getItem(TOKEN_KEY);\n"
    "  if (!t && window.location.hash.length > 1) {\n"
    "    t = decodeURIComponent(window.location.hash.substring(1));\n"
    "    if (t) { localStorage.setItem(TOKEN_KEY, t); window.location.hash = ''; }\n"
    "  }\n"
    "  return t;\n"
    "}\n"
    "\n"
    "function api(path, opts) {\n"
    "  const headers = {'Content-Type': 'application/json'};\n"
    "  const token = getToken();\n"
    "  if (token) headers['Authorization'] = 'Bearer ' + token;\n"
    "  return fetch(API_BASE + path, { ...opts, headers }).then(r => {\n"
    "    if (r.status === 401 && path !== '/api/v1/auth/login') {\n"
    "      logout();\n"
    "      throw new Error('认证过期');\n"
    "    }\n"
    "    return r.json();\n"
    "  });\n"
    "}\n"
    "\n"
    "function toast(msg, type) {\n"
    "  const c = document.getElementById('toastContainer');\n"
    "  const t = document.createElement('div');\n"
    "  t.className = 'toast toast-' + type;\n"
    "  t.textContent = msg;\n"
    "  c.appendChild(t);\n"
    "  setTimeout(() => t.remove(), 3000);\n"
    "}\n"
    "\n"
    "function closeModal(id) { document.getElementById(id).classList.remove('active'); }\n"
    "\n"
    "function showModal(id) { document.getElementById(id).classList.add('active'); }\n"
    "\n"
    "// Auth\n"
    "let currentUser = null;\n"
    "\n"
    "function checkAuth() {\n"
    "  const token = getToken();\n"
    "  if (!token) { window.location.href = '/login'; return; }\n"
    "  fetch('/api/v1/auth/verify', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token})}).then(r => {\n"
    "    if (!r.ok) throw new Error('verify failed');\n"
    "    return r.json();\n"
    "  }).then(d => {\n"
    "    if (!d.valid) throw new Error('invalid token');\n"
    "    currentUser = d;\n"
    "    document.getElementById('userInfo').innerHTML = '<strong>' + (d.display_name || d.username) + '</strong><br>' + (d.email || '');\n"
    "  }).catch(() => { window.location.href = '/login'; });\n"
    "}\n"
    "\n"
    "function logout() {\n"
    "  const token = getToken();\n"
    "  if (token) {\n"
    "    api('/api/v1/auth/logout', {method:'POST'}).catch(() => {});\n"
    "  }\n"
    "  localStorage.removeItem(TOKEN_KEY);\n"
    "  window.location.href = '/login';\n"
    "}\n"
    "\n"
    "// Section switching\n"
    "let currentSection = 'users';\n"
    "\n"
    "function switchSection(section) {\n"
    "  currentSection = section;\n"
    "  document.querySelectorAll('.section').forEach(s => s.classList.remove('active'));\n"
    "  document.getElementById('section-' + section).classList.add('active');\n"
    "  document.querySelectorAll('.sidebar nav a').forEach(a => a.classList.remove('active'));\n"
    "  document.querySelector('.sidebar nav a[data-section=\\\"' + section + '\\\"]').classList.add('active');\n"
    "  if (section === 'users') loadUsers();\n"
    "  else if (section === 'roles') loadRoles();\n"
    "  else if (section === 'policies') loadPolicies();\n"
    "  else if (section === 'groups') loadGroups();\n"
    "}\n"
    "\n"
    "// Generic helpers\n"
    "function htmlEncode(s) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\\\"/g,'&quot;'); }\n"
    "\n"
    "// ---- USERS ----\n"
    "let allUsers = [];\n"
    "\n"
    "function loadUsers() {\n"
    "  document.getElementById('userList').innerHTML = '<div class=\\\"loading\\\">加载中...</div>';\n"
    "  api('/api/v1/users').then(data => {\n"
    "    if (Array.isArray(data)) {\n"
    "      allUsers = data;\n"
    "      renderUsers(data);\n"
    "    } else {\n"
    "      document.getElementById('userList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "    }\n"
    "  }).catch(() => {\n"
    "    document.getElementById('userList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "  });\n"
    "}\n"
    "\n"
    "function renderUsers(users) {\n"
    "  document.getElementById('userCount').textContent = users.length;\n"
    "  if (users.length === 0) {\n"
    "    document.getElementById('userList').innerHTML = '<div class=\\\"empty-state\\\">暂无用户</div>';\n"
    "    return;\n"
    "  }\n"
    "  let html = '<table><thead><tr><th>ID</th><th>用户名</th><th>显示名称</th><th>邮箱</th><th>状态</th><th>角色</th><th>操作</th></tr></thead><tbody>';\n"
    "  users.forEach(u => {\n"
    "    let statusClass = 'status-active';\n"
    "    let statusText = '激活';\n"
    "    if (u.status === 0) { statusClass = 'status-disabled'; statusText = '禁用'; }\n"
    "    else if (u.status === 2) { statusClass = 'status-inactive'; statusText = '未激活'; }\n"
    "    const roleTags = (u.roles || []).map(r => '<span class=\\\"tag\\\">' + htmlEncode(r.name) + '</span>').join('');\n"
    "    html += '<tr><td>' + u.id + '</td><td><strong>' + htmlEncode(u.username) + '</strong></td><td>' + htmlEncode(u.display_name) + '</td><td>' + htmlEncode(u.email) + '</td>'\n"
    "      + '<td><span class=\\\"status-badge ' + statusClass + '\\\">' + statusText + '</span></td>'\n"
    "      + '<td>' + (roleTags || '<span style=\\\"color:#666\\\">无</span>') + '</td>'\n"
    "      + '<td><button class=\\\"btn btn-sm btn-primary\\\" onclick=\\\"showAssignRole(' + u.id + ')\\\">分配角色</button></td></tr>';\n"
    "  });\n"
    "  html += '</tbody></table>';\n"
    "  document.getElementById('userList').innerHTML = html;\n"
    "}\n"
    "\n"
    "function filterUsers() {\n"
    "  const q = document.getElementById('userSearch').value.toLowerCase();\n"
    "  const filtered = allUsers.filter(u => u.username.toLowerCase().includes(q) || u.display_name.toLowerCase().includes(q) || (u.email && u.email.toLowerCase().includes(q)));\n"
    "  renderUsers(filtered);\n"
    "}\n"
    "\n"
    "function showCreateUserModal() { showModal('createUserModal'); }\n"
    "\n"
    "function createUser() {\n"
    "  const username = document.getElementById('cuUsername').value.trim();\n"
    "  const password = document.getElementById('cuPassword').value;\n"
    "  if (!username || !password) { toast('用户名和密码为必填项', 'error'); return; }\n"
    "  api('/api/v1/users', {method:'POST', body:JSON.stringify({\n"
    "    username, password,\n"
    "    email: document.getElementById('cuEmail').value.trim(),\n"
    "    display_name: document.getElementById('cuDisplay').value.trim() || username\n"
    "  })}).then(data => {\n"
    "    if (data.created || data.user_id) {\n"
    "      toast('用户 ' + username + ' 创建成功', 'success');\n"
    "      closeModal('createUserModal');\n"
    "      document.getElementById('cuUsername').value = '';\n"
    "      document.getElementById('cuPassword').value = '';\n"
    "      document.getElementById('cuEmail').value = '';\n"
    "      document.getElementById('cuDisplay').value = '';\n"
    "      loadUsers();\n"
    "    } else { toast(data.error || '创建失败', 'error'); }\n"
    "  }).catch(() => toast('创建失败', 'error'));\n"
    "}\n"
    "\n"
    "function showAssignRole(userId) {\n"
    "  const user = allUsers.find(u => u.id === userId);\n"
    "  document.getElementById('assignRoleUser').textContent = '用户: ' + (user ? (user.display_name || user.username) : '#' + userId);\n"
    "  document.getElementById('assignRoleSelect').innerHTML = '<option value=\\\"\\\">选择角色...</option>';\n"
    "  api('/api/v1/roles').then(roles => {\n"
    "    if (Array.isArray(roles)) {\n"
    "      roles.forEach(r => {\n"
    "        const opt = document.createElement('option');\n"
    "        opt.value = r.id;\n"
    "        opt.textContent = r.name + (r.parent_name ? ' (' + r.parent_name + ')' : '');\n"
    "        document.getElementById('assignRoleSelect').appendChild(opt);\n"
    "      });\n"
    "    }\n"
    "  }).catch(() => {});\n"
    "  document.getElementById('assignRoleSelect').dataset.userId = userId;\n"
    "  showModal('assignRoleModal');\n"
    "}\n"
    "\n"
    "function assignRole() {\n"
    "  const sel = document.getElementById('assignRoleSelect');\n"
    "  const userId = parseInt(sel.dataset.userId);\n"
    "  const roleId = parseInt(sel.value);\n"
    "  if (!roleId) { toast('请选择角色', 'error'); return; }\n"
    "  api('/api/v1/roles/' + roleId + '/assign', {method:'POST', body:JSON.stringify({user_id: userId})})\n"
    "    .then(data => {\n"
    "      if (data.assigned) {\n"
    "        toast('角色分配成功', 'success');\n"
    "        closeModal('assignRoleModal');\n"
    "        loadUsers();\n"
    "      } else { toast(data.error || '分配失败', 'error'); }\n"
    "    }).catch(() => toast('分配失败', 'error'));\n"
    "}\n"
    "\n"
    "// ---- ROLES ----\n"
    "function loadRoles() {\n"
    "  document.getElementById('roleList').innerHTML = '<div class=\\\"loading\\\">加载中...</div>';\n"
    "  api('/api/v1/roles').then(data => {\n"
    "    if (Array.isArray(data)) {\n"
    "      document.getElementById('roleCount').textContent = data.length;\n"
    "      if (data.length === 0) {\n"
    "        document.getElementById('roleList').innerHTML = '<div class=\\\"empty-state\\\">暂无角色</div>';\n"
    "        return;\n"
    "      }\n"
    "      let html = '<table><thead><tr><th>ID</th><th>名称</th><th>描述</th><th>父角色</th><th>创建时间</th></tr></thead><tbody>';\n"
    "      data.forEach(r => {\n"
    "        html += '<tr><td>' + r.id + '</td><td><strong>' + htmlEncode(r.name) + '</strong></td>'\n"
    "          + '<td>' + htmlEncode(r.description || '-') + '</td>'\n"
    "          + '<td>' + (r.parent_name ? '<span class=\\\"tag tag-success\\\">' + htmlEncode(r.parent_name) + '</span>' : '<span style=\\\"color:#666\\\">-</span>') + '</td>'\n"
    "          + '<td style=\\\"color:#666;font-size:12px\\\">' + new Date(r.created_at).toLocaleString('zh-CN') + '</td></tr>';\n"
    "      });\n"
    "      html += '</tbody></table>';\n"
    "      document.getElementById('roleList').innerHTML = html;\n"
    "\n"
    "      // Also populate role selects in modals\n"
    "      populateRoleSelects(data);\n"
    "    } else {\n"
    "      document.getElementById('roleList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "    }\n"
    "  }).catch(() => {\n"
    "    document.getElementById('roleList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "  });\n"
    "}\n"
    "\n"
    "function populateRoleSelects(roles) {\n"
    "  const selects = ['crParent'];\n"
    "  selects.forEach(id => {\n"
    "    const sel = document.getElementById(id);\n"
    "    if (!sel) return;\n"
    "    const current = sel.value;\n"
    "    sel.innerHTML = '<option value=\\\"0\\\">无（顶级角色）</option>';\n"
    "    if (Array.isArray(roles)) {\n"
    "      roles.forEach(r => {\n"
    "        const opt = document.createElement('option');\n"
    "        opt.value = r.id;\n"
    "        opt.textContent = r.name + ' (#' + r.id + ')';\n"
    "        sel.appendChild(opt);\n"
    "      });\n"
    "    }\n"
    "    sel.value = current;\n"
    "  });\n"
    "}\n"
    "\n"
    "function showCreateRoleModal() {\n"
    "  api('/api/v1/roles').then(roles => {\n"
    "    if (Array.isArray(roles)) populateRoleSelects(roles);\n"
    "  }).catch(() => {});\n"
    "  showModal('createRoleModal');\n"
    "}\n"
    "\n"
    "function createRole() {\n"
    "  const name = document.getElementById('crName').value.trim();\n"
    "  if (!name) { toast('角色名称为必填项', 'error'); return; }\n"
    "  api('/api/v1/roles', {method:'POST', body:JSON.stringify({\n"
    "    name,\n"
    "    description: document.getElementById('crDesc').value.trim(),\n"
    "    parent_role_id: parseInt(document.getElementById('crParent').value) || 0\n"
    "  })}).then(data => {\n"
    "    if (data.created || data.role_id) {\n"
    "      toast('角色 ' + name + ' 创建成功', 'success');\n"
    "      closeModal('createRoleModal');\n"
    "      document.getElementById('crName').value = '';\n"
    "      document.getElementById('crDesc').value = '';\n"
    "      loadRoles();\n"
    "    } else { toast(data.error || '创建失败', 'error'); }\n"
    "  }).catch(() => toast('创建失败', 'error'));\n"
    "}\n"
    "\n"
    "// ---- POLICIES ----\n"
    "function loadPolicies() {\n"
    "  document.getElementById('policyList').innerHTML = '<div class=\\\"loading\\\">加载中...</div>';\n"
    "  api('/api/v1/policies').then(data => {\n"
    "    if (Array.isArray(data)) {\n"
    "      document.getElementById('policyCount').textContent = data.length;\n"
    "      if (data.length === 0) {\n"
    "        document.getElementById('policyList').innerHTML = '<div class=\\\"empty-state\\\">暂无策略</div>';\n"
    "        return;\n"
    "      }\n"
    "      let html = '<table><thead><tr><th>ID</th><th>名称</th><th>类型</th><th>效果</th><th>优先级</th><th>状态</th><th>操作</th></tr></thead><tbody>';\n"
    "      data.forEach(p => {\n"
    "        let effectHtml = p.effect === 1 ? '<span class=\\\"tag tag-success\\\">ALLOW</span>' : '<span class=\\\"tag tag-danger\\\">DENY</span>';\n"
    "        let statusHtml = p.status === 1 ? '<span class=\\\"tag tag-success\\\">启用</span>' : '<span class=\\\"tag tag-warning\\\">禁用</span>';\n"
    "        let typeMap = {1:'FUNCTIONAL', 2:'API', 3:'DATA'};\n"
    "        let typeTags = [];\n"
    "        if (p.strategy_type === 1) typeTags.push('<span class=\\\"tag\\\">功能</span>');\n"
    "        else if (p.strategy_type === 2) typeTags.push('<span class=\\\"tag tag-warning\\\">API</span>');\n"
    "        else if (p.strategy_type === 3) typeTags.push('<span class=\\\"tag tag-success\\\">数据</span>');\n"
    "        html += '<tr><td>' + p.id + '</td><td><strong>' + htmlEncode(p.name) + '</strong></td>'\n"
    "          + '<td>' + typeTags.join('') + '</td>'\n"
    "          + '<td>' + effectHtml + '</td>'\n"
    "          + '<td>' + p.priority + '</td>'\n"
    "          + '<td>' + statusHtml + '</td>'\n"
    "          + '<td><button class=\\\"btn btn-sm btn-primary\\\" onclick=\\\"showAssignPolicy(' + p.id + ')\\\">分配</button></td></tr>';\n"
    "      });\n"
    "      html += '</tbody></table>';\n"
    "      document.getElementById('policyList').innerHTML = html;\n"
    "    } else {\n"
    "      document.getElementById('policyList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "    }\n"
    "  }).catch(() => {\n"
    "    document.getElementById('policyList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "  });\n"
    "}\n"
    "\n"
    "function showCreatePolicyModal() { showModal('createPolicyModal'); }\n"
    "\n"
    "function createPolicy() {\n"
    "  const name = document.getElementById('cpName').value.trim();\n"
    "  if (!name) { toast('策略名称为必填项', 'error'); return; }\n"
    "  const rulesStr = document.getElementById('cpRules').value.trim();\n"
    "  let rules;\n"
    "  try { rules = rulesStr ? JSON.parse(rulesStr) : {}; } catch(e) { toast('规则 JSON 格式错误', 'error'); return; }\n"
    "  api('/api/v1/policies', {method:'POST', body:JSON.stringify({\n"
    "    name,\n"
    "    strategy_type: parseInt(document.getElementById('cpStrategy').value),\n"
    "    effect: parseInt(document.getElementById('cpEffect').value),\n"
    "    priority: parseInt(document.getElementById('cpPriority').value) || 50,\n"
    "    rules: JSON.stringify(rules)\n"
    "  })}).then(data => {\n"
    "    if (data.created || data.policy_id) {\n"
    "      toast('策略 ' + name + ' 创建成功', 'success');\n"
    "      closeModal('createPolicyModal');\n"
    "      document.getElementById('cpName').value = '';\n"
    "      document.getElementById('cpRules').value = '';\n"
    "      loadPolicies();\n"
    "    } else { toast(data.error || '创建失败', 'error'); }\n"
    "  }).catch(() => toast('创建失败', 'error'));\n"
    "}\n"
    "\n"
    "function showAssignPolicy(policyId) {\n"
    "  document.getElementById('assignPolicyInfo').textContent = '策略 ID: ' + policyId;\n"
    "  document.getElementById('apTargetId').value = '';\n"
    "  document.getElementById('assignPolicySelect') && document.getElementById('assignPolicySelect').value && (document.getElementById('assignPolicySelect').value = '');\n"
    "  document.getElementById('assignPolicyInfo').dataset.policyId = policyId;\n"
    "  showModal('assignPolicyModal');\n"
    "}\n"
    "\n"
    "function assignPolicy() {\n"
    "  const policyId = parseInt(document.getElementById('assignPolicyInfo').dataset.policyId);\n"
    "  const targetType = parseInt(document.getElementById('apTargetType').value);\n"
    "  const targetId = parseInt(document.getElementById('apTargetId').value);\n"
    "  if (!targetId) { toast('请输入目标 ID', 'error'); return; }\n"
    "  api('/api/v1/policies/' + policyId + '/assign', {method:'POST', body:JSON.stringify({target_type: targetType, target_id: targetId})})\n"
    "    .then(data => {\n"
    "      if (data.assigned) {\n"
    "        toast('策略分配成功', 'success');\n"
    "        closeModal('assignPolicyModal');\n"
    "      } else { toast(data.error || '分配失败', 'error'); }\n"
    "    }).catch(() => toast('分配失败', 'error'));\n"
    "}\n"
    "\n"
    "// ---- GROUPS ----\n"
    "function loadGroups() {\n"
    "  document.getElementById('groupList').innerHTML = '<div class=\\\"loading\\\">加载中...</div>';\n"
    "  api('/api/v1/groups').then(data => {\n"
    "    if (Array.isArray(data)) {\n"
    "      document.getElementById('groupCount').textContent = data.length;\n"
    "      if (data.length === 0) {\n"
    "        document.getElementById('groupList').innerHTML = '<div class=\\\"empty-state\\\">暂无分组</div>';\n"
    "        return;\n"
    "      }\n"
    "      let html = '<table><thead><tr><th>ID</th><th>名称</th><th>描述</th><th>父分组</th><th>创建时间</th></tr></thead><tbody>';\n"
    "      data.forEach(g => {\n"
    "        html += '<tr><td>' + g.id + '</td><td><strong>' + htmlEncode(g.name) + '</strong></td>'\n"
    "          + '<td>' + htmlEncode(g.description || '-') + '</td>'\n"
    "          + '<td>' + (g.parent_name ? '<span class=\\\"tag tag-success\\\">' + htmlEncode(g.parent_name) + '</span>' : '<span style=\\\"color:#666\\\">-</span>') + '</td>'\n"
    "          + '<td style=\\\"color:#666;font-size:12px\\\">' + new Date(g.created_at).toLocaleString('zh-CN') + '</td></tr>';\n"
    "      });\n"
    "      html += '</tbody></table>';\n"
    "      document.getElementById('groupList').innerHTML = html;\n"
    "      populateGroupSelects(data);\n"
    "    } else {\n"
    "      document.getElementById('groupList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "    }\n"
    "  }).catch(() => {\n"
    "    document.getElementById('groupList').innerHTML = '<div class=\\\"empty-state\\\">加载失败</div>';\n"
    "  });\n"
    "}\n"
    "\n"
    "function populateGroupSelects(groups) {\n"
    "  const sel = document.getElementById('cgParent');\n"
    "  if (!sel) return;\n"
    "  sel.innerHTML = '<option value=\\\"0\\\">无（顶级分组）</option>';\n"
    "  if (Array.isArray(groups)) {\n"
    "    groups.forEach(g => {\n"
    "      const opt = document.createElement('option');\n"
    "      opt.value = g.id;\n"
    "      opt.textContent = g.name + ' (#' + g.id + ')';\n"
    "      sel.appendChild(opt);\n"
    "    });\n"
    "  }\n"
    "}\n"
    "\n"
    "function showCreateGroupModal() {\n"
    "  api('/api/v1/groups').then(groups => {\n"
    "    if (Array.isArray(groups)) populateGroupSelects(groups);\n"
    "  }).catch(() => {});\n"
    "  showModal('createGroupModal');\n"
    "}\n"
    "\n"
    "function createGroup() {\n"
    "  const name = document.getElementById('cgName').value.trim();\n"
    "  if (!name) { toast('分组名称为必填项', 'error'); return; }\n"
    "  api('/api/v1/groups', {method:'POST', body:JSON.stringify({\n"
    "    name,\n"
    "    description: document.getElementById('cgDesc').value.trim(),\n"
    "    parent_group_id: parseInt(document.getElementById('cgParent').value) || 0\n"
    "  })}).then(data => {\n"
    "    if (data.created || data.group_id || data.id) {\n"
    "      toast('分组 ' + name + ' 创建成功', 'success');\n"
    "      closeModal('createGroupModal');\n"
    "      document.getElementById('cgName').value = '';\n"
    "      document.getElementById('cgDesc').value = '';\n"
    "      loadGroups();\n"
    "    } else { toast(data.error || '创建失败', 'error'); }\n"
    "  }).catch(() => toast('创建失败', 'error'));\n"
    "}\n"
    "\n"
    "// Init\n"
    "checkAuth();\n"
    "loadUsers();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n"
;

#endif /* SSO_ADMIN_PAGE_H */
