/*
 * admin_page.h — Built-in admin management page HTML (auto-generated)
 */
#ifndef SSO_ADMIN_PAGE_H
#define SSO_ADMIN_PAGE_H

static const char ADMIN_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>SSO 管理后台</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    ":root{\n"
    "  --bg-dark:#0f111a;\n"
    "  --bg-card:#161925;\n"
    "  --bg-sidebar:#1a1d2c;\n"
    "  --bg-input:#1f2335;\n"
    "  --accent:#7aa2f7;\n"
    "  --accent-light:#bb9af7;\n"
    "  --accent-gradient:linear-gradient(135deg, #7aa2f7, #bb9af7);\n"
    "  --text-main:#a9b1d6;\n"
    "  --text-bright:#c0caf5;\n"
    "  --text-muted:#565f89;\n"
    "  --border:#292e42;\n"
    "  --success:#9ece6a;\n"
    "  --error:#f7768e;\n"
    "  --warning:#e0af68;\n"
    "  --radius:12px;\n"
    "  --shadow:0 10px 30px rgba(0,0,0,0.5);\n"
    "}\n"
    "body{\n"
    "  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;\n"
    "  background:var(--bg-dark);\n"
    "  color:var(--text-main);\n"
    "  min-height:100vh;\n"
    "  display:none; /* Hide until auth check */\n"
    "  overflow:hidden;\n"
    "}\n"
    ".sidebar{\n"
    "  width:260px;\n"
    "  background:var(--bg-sidebar);\n"
    "  border-right:1px solid var(--border);\n"
    "  display:flex;\n"
    "  flex-direction:column;\n"
    "  flex-shrink:0;\n"
    "  z-index:100;\n"
    "}\n"
    ".sidebar-header{\n"
    "  padding:40px 24px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:12px;\n"
    "}\n"
    ".logo-icon{\n"
    "  width:36px;\n"
    "  height:36px;\n"
    "  background:var(--accent-gradient);\n"
    "  border-radius:10px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  color:#fff;\n"
    "  font-weight:bold;\n"
    "  font-size:20px;\n"
    "  box-shadow:0 0 20px rgba(122,162,247,0.3);\n"
    "}\n"
    ".logo-text{\n"
    "  font-size:20px;\n"
    "  font-weight:800;\n"
    "  color:var(--text-bright);\n"
    "  letter-spacing:-0.5px;\n"
    "}\n"
    ".nav-links{\n"
    "  padding:0 16px;\n"
    "  flex:1;\n"
    "}\n"
    ".nav-item{\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:12px;\n"
    "  padding:14px 16px;\n"
    "  color:var(--text-main);\n"
    "  text-decoration:none;\n"
    "  border-radius:var(--radius);\n"
    "  margin-bottom:6px;\n"
    "  transition:all 0.2s;\n"
    "  cursor:pointer;\n"
    "  font-size:14px;\n"
    "  font-weight:500;\n"
    "}\n"
    ".nav-item:hover{\n"
    "  background:rgba(255,255,255,0.04);\n"
    "  color:var(--text-bright);\n"
    "}\n"
    ".nav-item.active{\n"
    "  background:rgba(122,162,247,0.1);\n"
    "  color:var(--accent);\n"
    "}\n"
    ".sidebar-footer{\n"
    "  padding:24px;\n"
    "  border-top:1px solid var(--border);\n"
    "  background:rgba(0,0,0,0.1);\n"
    "}\n"
    ".user-profile{\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:12px;\n"
    "  margin-bottom:20px;\n"
    "}\n"
    ".user-avatar{\n"
    "  width:40px;\n"
    "  height:40px;\n"
    "  background:var(--bg-input);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:12px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  color:var(--accent);\n"
    "  font-weight:bold;\n"
    "}\n"
    ".user-meta{\n"
    "  flex:1;\n"
    "  min-width:0;\n"
    "}\n"
    ".user-name{\n"
    "  font-size:14px;\n"
    "  font-weight:600;\n"
    "  color:var(--text-bright);\n"
    "  white-space:nowrap;\n"
    "  overflow:hidden;\n"
    "  text-overflow:ellipsis;\n"
    "}\n"
    ".user-role{\n"
    "  font-size:11px;\n"
    "  color:var(--text-muted);\n"
    "}\n"
    "/* Main Content */\n"
    ".main{\n"
    "  flex:1;\n"
    "  display:flex;\n"
    "  flex-direction:column;\n"
    "  overflow:hidden;\n"
    "}\n"
    ".top-bar{\n"
    "  height:72px;\n"
    "  padding:0 40px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:space-between;\n"
    "  border-bottom:1px solid var(--border);\n"
    "  background:rgba(15, 17, 26, 0.7);\n"
    "  backdrop-filter:blur(20px);\n"
    "}\n"
    ".controls-bar{\n"
    "  padding:16px 40px;\n"
    "  display:flex;\n"
    "  gap:16px;\n"
    "  background:rgba(26, 27, 38, 0.5);\n"
    "  border-bottom:1px solid var(--border);\n"
    "  align-items:center;\n"
    "}\n"
    ".search-box{\n"
    "  flex:1;\n"
    "  max-width:400px;\n"
    "  position:relative;\n"
    "}\n"
    ".search-box input{\n"
    "  width:100%;\n"
    "  padding-left:40px;\n"
    "}\n"
    ".search-box::before{\n"
    "  content:'🔍';\n"
    "  position:absolute;\n"
    "  left:14px;\n"
    "  top:50%;\n"
    "  transform:translateY(-50%);\n"
    "  opacity:0.5;\n"
    "}\n"
    ".content-area{\n"
    "  flex:1;\n"
    "  padding:20px 40px;\n"
    "  overflow-y:auto;\n"
    "}\n"
    ".pagination-bar{\n"
    "  padding:16px 40px;\n"
    "  display:flex;\n"
    "  justify-content:space-between;\n"
    "  align-items:center;\n"
    "  border-top:1px solid var(--border);\n"
    "  background:rgba(15, 17, 26, 0.5);\n"
    "  font-size:13px;\n"
    "}\n"
    ".grid{\n"
    "  display:grid;\n"
    "  grid-template-columns:repeat(auto-fill, minmax(280px, 1fr));\n"
    "  gap:24px;\n"
    "  margin-bottom:40px;\n"
    "}\n"
    "/* Stats Card */\n"
    ".stat-card{\n"
    "  background:var(--bg-card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:16px;\n"
    "  padding:24px;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  gap:20px;\n"
    "}\n"
    ".stat-icon{\n"
    "  width:56px;\n"
    "  height:56px;\n"
    "  border-radius:14px;\n"
    "  background:var(--bg-input);\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  font-size:24px;\n"
    "  color:var(--accent);\n"
    "}\n"
    ".stat-info .stat-label{\n"
    "  font-size:12px;\n"
    "  color:var(--text-muted);\n"
    "  font-weight:600;\n"
    "  text-transform:uppercase;\n"
    "  letter-spacing:1px;\n"
    "  margin-bottom:6px;\n"
    "}\n"
    ".stat-info .stat-value{\n"
    "  font-size:28px;\n"
    "  font-weight:800;\n"
    "  color:var(--text-bright);\n"
    "}\n"
    "/* Table Card */\n"
    ".card{\n"
    "  background:var(--bg-card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:16px;\n"
    "  overflow:hidden;\n"
    "  box-shadow:var(--shadow);\n"
    "}\n"
    ".card-header{\n"
    "  padding:24px 32px;\n"
    "  border-bottom:1px solid var(--border);\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:space-between;\n"
    "}\n"
    ".card-title{\n"
    "  font-size:18px;\n"
    "  font-weight:700;\n"
    "  color:var(--text-bright);\n"
    "}\n"
    ".table-wrapper{\n"
    "  overflow-x:auto;\n"
    "}\n"
    "table{\n"
    "  width:100%;\n"
    "  border-collapse:collapse;\n"
    "}\n"
    "th{\n"
    "  background:rgba(0,0,0,0.15);\n"
    "  padding:14px 32px;\n"
    "  text-align:left;\n"
    "  font-size:12px;\n"
    "  text-transform:uppercase;\n"
    "  color:var(--text-muted);\n"
    "  font-weight:700;\n"
    "  letter-spacing:1px;\n"
    "}\n"
    "td{\n"
    "  padding:18px 32px;\n"
    "  border-bottom:1px solid var(--border);\n"
    "  font-size:14px;\n"
    "  color:var(--text-main);\n"
    "}\n"
    "tr:last-child td{border-bottom:none}\n"
    "tr:hover td{background:rgba(255,255,255,0.015)}\n"
    "/* Components */\n"
    ".btn{\n"
    "  display:inline-flex;\n"
    "  align-items:center;\n"
    "  gap:8px;\n"
    "  padding:10px 20px;\n"
    "  border-radius:var(--radius);\n"
    "  font-size:14px;\n"
    "  font-weight:600;\n"
    "  cursor:pointer;\n"
    "  transition:all 0.2s;\n"
    "  border:none;\n"
    "  outline:none;\n"
    "}\n"
    ".btn-primary{\n"
    "  background:var(--accent-gradient);\n"
    "  color:#fff;\n"
    "  box-shadow:0 4px 15px rgba(122,162,247,0.3);\n"
    "}\n"
    ".btn-primary:hover{opacity:0.9;transform:translateY(-1px);box-shadow:0 6px 20px rgba(122,162,247,0.4)}\n"
    ".btn-outline{\n"
    "  background:rgba(255,255,255,0.03);\n"
    "  border:1px solid var(--border);\n"
    "  color:var(--text-bright);\n"
    "}\n"
    ".btn-outline:hover{background:var(--bg-input);border-color:var(--text-muted)}\n"
    ".btn-danger{\n"
    "  background:rgba(247,118,142,0.1);\n"
    "  color:var(--error);\n"
    "  border: 1px solid rgba(247,118,142,0.1);\n"
    "}\n"
    ".btn-danger:hover{background:var(--error);color:#fff}\n"
    ".btn-sm{padding:6px 12px;font-size:12px;border-radius:6px}\n"
    "\n"
    ".status-pill{\n"
    "  display:inline-flex;\n"
    "  align-items:center;\n"
    "  gap:6px;\n"
    "  font-size:12px;\n"
    "  font-weight:600;\n"
    "  padding:4px 12px;\n"
    "  border-radius:20px;\n"
    "}\n"
    ".status-active{background:rgba(158,206,106,0.1);color:var(--success)}\n"
    ".status-inactive{background:rgba(247,118,142,0.1);color:var(--error)}\n"
    "\n"
    ".tag{\n"
    "  padding:2px 8px;\n"
    "  border-radius:4px;\n"
    "  font-size:11px;\n"
    "  font-weight:600;\n"
    "  background:rgba(122,162,247,0.1);\n"
    "  color:var(--accent);\n"
    "  margin-right: 4px;\n"
    "}\n"
    "\n"
    "/* Modal */\n"
    ".modal-overlay{\n"
    "  position:fixed;\n"
    "  inset:0;\n"
    "  background:rgba(0,0,0,0.8);\n"
    "  backdrop-filter:blur(8px);\n"
    "  display:none;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  z-index:1000;\n"
    "}\n"
    ".modal-overlay.active{display:flex}\n"
    ".modal{\n"
    "  background:var(--bg-card);\n"
    "  border:1px solid var(--border);\n"
    "  width:640px;\n"
    "  max-width:95%;\n"
    "  border-radius:20px;\n"
    "  padding:40px;\n"
    "  box-shadow:0 30px 60px rgba(0,0,0,0.6);\n"
    "  max-height: 90vh;\n"
    "  overflow-y: auto;\n"
    "}\n"
    ".modal h3{font-size:22px;color:var(--text-bright);font-weight:700;margin-bottom:8px}\n"
    ".modal p{font-size:14px;color:var(--text-muted);margin-bottom:24px}\n"
    ".form-group{margin-bottom:24px}\n"
    ".form-group label{display:block;font-size:13px;font-weight:600;color:var(--text-muted);margin-bottom:10px;text-transform:uppercase;letter-spacing:0.5px}\n"
    "input, select, textarea{\n"
    "  width:100%;\n"
    "  background:var(--bg-input);\n"
    "  border:1px solid var(--border);\n"
    "  padding:14px 18px;\n"
    "  border-radius:var(--radius);\n"
    "  color:var(--text-bright);\n"
    "  font-size:15px;\n"
    "  outline:none;\n"
    "  transition:all 0.2s;\n"
    "}\n"
    "input:focus, select:focus, textarea:focus{border-color:var(--accent);box-shadow:0 0 0 4px rgba(122,162,247,0.15)}\n"
    ".modal-footer{\n"
    "  display:flex;\n"
    "  justify-content:flex-end;\n"
    "  gap:12px;\n"
    "  margin-top:40px;\n"
    "}\n"
    "/* Rule Builder UI */\n"
    ".rule-builder{\n"
    "  background:var(--bg-dark);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:var(--radius);\n"
    "  padding:16px;\n"
    "  margin-top:10px;\n"
    "}\n"
    ".rule-item{\n"
    "  display:flex;\n"
    "  gap:10px;\n"
    "  margin-bottom:10px;\n"
    "  align-items: center;\n"
    "}\n"
    ".rule-item input, .rule-item select{ padding: 10px; font-size: 13px; }\n"
    "\n"
    "/* Toast */\n"
    ".toast-container{position:fixed;top:20px;right:20px;z-index:2000}\n"
    ".toast{padding:12px 24px;border-radius:8px;background:var(--bg-card);color:#fff;border:1px solid var(--border);box-shadow:var(--shadow);margin-bottom:10px;transition:opacity 0.3s;}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div class=\"sidebar\">\n"
    "  <div class=\"sidebar-header\">\n"
    "    <div class=\"logo-icon\">S</div>\n"
    "    <div class=\"logo-text\">SSO Admin</div>\n"
    "  </div>\n"
    "  <div class=\"nav-links\">\n"
    "    <div class=\"nav-item active\" id=\"nav-users\" onclick=\"switchTab('users')\"><span>👥</span> 用户管理</div>\n"
    "    <div class=\"nav-item\" id=\"nav-roles\" onclick=\"switchTab('roles')\"><span>🔐</span> 角色管理</div>\n"
    "    <div class=\"nav-item\" id=\"nav-groups\" onclick=\"switchTab('groups')\"><span>🏢</span> 组织架构</div>\n"
    "    <div class=\"nav-item\" id=\"nav-policies\" onclick=\"switchTab('policies')\"><span>📜</span> 策略配置</div>\n"
    "    <div class=\"nav-item\" id=\"nav-audit\" onclick=\"switchTab('audit')\"><span>🔍</span> 审计日志</div>\n"
    "    <div class=\"nav-item\" id=\"nav-metrics\" onclick=\"switchTab('metrics')\"><span>📊</span> 系统指标</div>\n"
    "  </div>\n"
    "  <div class=\"sidebar-footer\">\n"
    "    <div class=\"user-profile\">\n"
    "      <div class=\"user-avatar\" id=\"avatar\">A</div>\n"
    "      <div class=\"user-meta\">\n"
    "        <div class=\"user-name\" id=\"adminName\">Administrator</div>\n"
    "        <div class=\"user-role\">Super Admin</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div style=\"display:flex;flex-direction:column;gap:8px\">\n"
    "      <button class=\"btn btn-outline\" style=\"width:100%;justify-content:center\" onclick=\"showChangePass()\">修改密码</button>\n"
    "      <button class=\"btn btn-outline\" style=\"width:100%;justify-content:center\" onclick=\"logout()\">退出登录</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div class=\"main\">\n"
    "  <div class=\"top-bar\">\n"
    "    <div class=\"page-title\" id=\"pageTitle\">用户管理</div>\n"
    "    <div class=\"top-actions\">\n"
    "      <button class=\"btn btn-primary\" id=\"addBtn\" onclick=\"handleAdd()\">+ 新增用户</button>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"controls-bar\">\n"
    "    <div class=\"search-box\">\n"
    "      <input type=\"text\" id=\"searchInput\" placeholder=\"搜索关键词...\" oninput=\"handleSearch()\">\n"
    "    </div>\n"
    "    <div style=\"width:180px\">\n"
    "      <select id=\"statusFilter\" onchange=\"handleFilter()\">\n"
    "        <option value=\"-1\">所有状态</option>\n"
    "        <option value=\"1\">正常/激活</option>\n"
    "        <option value=\"0\">禁用/未激活</option>\n"
    "        <option value=\"2\">已锁定</option>\n"
    "      </select>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"content-area\">\n"
    "    <div class=\"grid\">\n"
    "      <div class=\"stat-card\">\n"
    "        <div class=\"stat-icon\">👥</div>\n"
    "        <div class=\"stat-info\"><div class=\"stat-label\">总用户数</div><div class=\"stat-value\" id=\"countUsers\">0</div></div>\n"
    "      </div>\n"
    "      <div class=\"stat-card\">\n"
    "        <div class=\"stat-icon\">🛡️</div>\n"
    "        <div class=\"stat-info\"><div class=\"stat-label\">活跃策略</div><div class=\"stat-value\" id=\"countPolicies\">0</div></div>\n"
    "      </div>\n"
    "      <div class=\"stat-card\">\n"
    "        <div class=\"stat-icon\">⚡</div>\n"
    "        <div class=\"stat-info\"><div class=\"stat-label\">鉴权次数</div><div class=\"stat-value\" id=\"totalEvals\">0</div></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"card\">\n"
    "      <div class=\"card-header\"><div class=\"card-title\">数据概览</div></div>\n"
    "      <div class=\"table-wrapper\" id=\"tableContainer\">\n"
    "        <div style=\"padding:60px;text-align:center;color:var(--text-muted)\">正在同步 SSO 核心数据...</div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"pagination-bar\">\n"
    "    <div id=\"pageInfo\">第 1 页，共 0 条</div>\n"
    "    <div style=\"display:flex;gap:12px\">\n"
    "      <button class=\"btn btn-outline btn-sm\" id=\"prevBtn\" onclick=\"changePage(-1)\">上一页</button>\n"
    "      <button class=\"btn btn-outline btn-sm\" id=\"nextBtn\" onclick=\"changePage(1)\">下一页</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div id=\"toastContainer\" class=\"toast-container\"></div>\n"
    "\n"
    "<div class=\"modal-overlay\" id=\"modalOverlay\">\n"
    "  <div class=\"modal\">\n"
    "    <h3 id=\"modalTitle\">标题</h3>\n"
    "    <p id=\"modalSub\">描述文字</p>\n"
    "    <div id=\"modalContent\"></div>\n"
    "    <div class=\"modal-footer\">\n"
    "      <button class=\"btn btn-outline\" onclick=\"closeModal()\">取消</button>\n"
    "      <button class=\"btn btn-primary\" id=\"confirmBtn\">确定提交</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "let currentTab = 'users';\n"
    "const TOKEN_KEY = 'sso_token';\n"
    "let allData = { users:[], roles:[], groups:[], policies:[] };\n"
    "let policyRules = [];\n"
    "\n"
    "let state = {\n"
    "  users: { page: 1, q: '', status: -1, total: 0 },\n"
    "  roles: { page: 1, q: '', status: -1, total: 0 },\n"
    "  groups: { page: 1, q: '', status: -1, total: 0 },\n"
    "  policies: { page: 1, q: '', status: -1, total: 0 },\n"
    "  audit: { page: 1, q: '', status: -1, total: 0 }\n"
    "};\n"
    "const LIMIT = 20;\n"
    "\n"
    "function handleSearch() {\n"
    "  const q = document.getElementById('searchInput').value;\n"
    "  state[currentTab].q = q;\n"
    "  state[currentTab].page = 1;\n"
    "  loadData();\n"
    "}\n"
    "\n"
    "function handleFilter() {\n"
    "  const s = parseInt(document.getElementById('statusFilter').value);\n"
    "  state[currentTab].status = s;\n"
    "  state[currentTab].page = 1;\n"
    "  loadData();\n"
    "}\n"
    "\n"
    "function changePage(delta) {\n"
    "  const s = state[currentTab];\n"
    "  const newPage = s.page + delta;\n"
    "  const totalPages = Math.max(1, Math.ceil(s.total / LIMIT));\n"
    "  if (newPage < 1 || newPage > totalPages) return;\n"
    "  s.page = newPage;\n"
    "  loadData();\n"
    "}\n"
    "\n"
    "function updatePaginationUI() {\n"
    "  const s = state[currentTab];\n"
    "  if (currentTab === 'metrics') {\n"
    "    document.querySelector('.pagination-bar').style.display = 'none';\n"
    "    return;\n"
    "  }\n"
    "  document.querySelector('.pagination-bar').style.display = 'flex';\n"
    "  const totalPages = Math.max(1, Math.ceil(s.total / LIMIT));\n"
    "  document.getElementById('pageInfo').textContent = `第 ${s.page} 页，共 ${s.total} 条 (共 ${totalPages} 页)`;\n"
    "  document.getElementById('prevBtn').disabled = s.page <= 1;\n"
    "  document.getElementById('nextBtn').disabled = s.page >= totalPages;\n"
    "}\n"
    "\n"
    "function toast(msg, type='success') {\n"
    "  const container = document.getElementById('toastContainer');\n"
    "  const t = document.createElement('div');\n"
    "  t.className = 'toast';\n"
    "  t.style.borderLeft = `4px solid var(--${type === 'success' ? 'success' : 'error'})`;\n"
    "  t.textContent = msg;\n"
    "  container.appendChild(t);\n"
    "  setTimeout(() => { t.style.opacity = '0'; setTimeout(() => t.remove(), 300); }, 3000);\n"
    "}\n"
    "\n"
    "function switchTab(tab) {\n"
    "  currentTab = tab;\n"
    "  document.querySelectorAll('.nav-item').forEach(i => i.classList.remove('active'));\n"
    "  const el = document.getElementById('nav-' + tab);\n"
    "  if(el) el.classList.add('active');\n"
    "  \n"
    "  // Sync UI controls with state\n"
    "  const s = state[tab] || { q: '', status: -1 };\n"
    "  document.getElementById('searchInput').value = s.q || '';\n"
    "  document.getElementById('statusFilter').value = (s.status !== undefined && s.status !== null) ? s.status : -1;\n"
    "\n"
    "  const labels = { 'users': '用户管理', 'roles': '角色管理', 'groups': '组织架构', 'policies': '策略配置', 'audit': '审计日志', 'metrics': '系统指标' };\n"
    "  document.getElementById('pageTitle').textContent = labels[tab];\n"
    "  const addBtn = document.getElementById('addBtn');\n"
    "  addBtn.textContent = '+ 新增' + labels[tab].substring(0, 2);\n"
    "  addBtn.style.display = (tab === 'metrics' || tab === 'audit') ? 'none' : 'flex';\n"
    "  loadData();\n"
    "}\n"
    "\n"
    "async function api(path, method='GET', body=null) {\n"
    "  const token = localStorage.getItem(TOKEN_KEY);\n"
    "  const headers = {'Content-Type':'application/json'};\n"
    "  if(token) headers['Authorization'] = 'Bearer ' + token;\n"
    "  try {\n"
    "    const r = await fetch(path, {method, headers, body: body ? JSON.stringify(body) : null});\n"
    "    if(r.status === 401) { logout(); return; }\n"
    "    \n"
    "    // Extract new tokens from headers if present\n"
    "    const accessToken = r.headers.get('X-SSO-Access-Token');\n"
    "    if(accessToken) localStorage.setItem(TOKEN_KEY, accessToken);\n"
    "    \n"
    "    const data = await r.json();\n"
    "    if(!r.ok) throw new Error(data.error || '请求失败');\n"
    "    return data;\n"
    "  } catch(e) { toast(e.message, 'error'); throw e; }\n"
    "}\n"
    "\n"
    "function loadData() {\n"
    "  const container = document.getElementById('tableContainer');\n"
    "  container.innerHTML = '<div style=\"padding:60px;text-align:center;color:var(--text-muted)\">加载中...</div>';\n"
    "  \n"
    "  const s = state[currentTab] || { page: 1, q: '', status: -1 };\n"
    "  const query = `?page=${s.page}&limit=${LIMIT}&q=${encodeURIComponent(s.q)}&status=${s.status}`;\n"
    "\n"
    "  if(currentTab === 'users') {\n"
    "    api('api/v1/users' + query).then(res => {\n"
    "      const data = res.items;\n"
    "      state.users.total = res.total;\n"
    "      allData.users = data;\n"
    "      updatePaginationUI();\n"
    "      document.getElementById('countUsers').textContent = res.total;\n"
    "      let html = '<table><thead><tr><th>ID</th><th>用户名</th><th>显示名称</th><th>状态</th><th>角色/分组</th><th>操作</th></tr></thead><tbody>';\n"
    "      data.forEach(u => {\n"
    "        const roles = (u.roles || []).map(r => `<span class=\"tag\">${r.name}</span>`).join('');\n"
    "        html += `<tr><td>#${u.id}</td><td style=\"color:var(--text-bright);font-weight:600\">${u.username}</td><td>${u.display_name||'-'}</td><td><span class=\"status-pill ${u.status === 1 ? 'status-active' : 'status-inactive'}\">${u.status === 1 ? '● 正常' : '● 禁用'}</span></td><td>${roles||'-'}</td><td>\n"
    "          <button class=\"btn btn-outline btn-sm\" onclick=\"showEditUser(${u.id})\">编辑</button>\n"
    "          <button class=\"btn btn-outline btn-sm\" onclick=\"showAssignments(${u.id})\">角色/群组</button>\n"
    "          <button class=\"btn btn-danger btn-sm\" onclick=\"deleteItem('users', ${u.id})\">删除</button>\n"
    "        </td></tr>`;\n"
    "      });\n"
    "      container.innerHTML = html + '</tbody></table>';\n"
    "    });\n"
    "  } else if(currentTab === 'roles') {\n"
    "    api('api/v1/roles' + query).then(res => {\n"
    "      const data = res.items;\n"
    "      state.roles.total = res.total;\n"
    "      allData.roles = data;\n"
    "      updatePaginationUI();\n"
    "      let html = '<table><thead><tr><th>ID</th><th>角色名称</th><th>父角色</th><th>描述</th><th>操作</th></tr></thead><tbody>';\n"
    "      data.forEach(r => {\n"
    "        html += `<tr><td>#${r.id}</td><td style=\"color:var(--text-bright);font-weight:600\">${r.name}</td><td>${r.parent_name||'-'}</td><td>${r.description||'-'}</td><td>\n"
    "          <button class=\"btn btn-outline btn-sm\" onclick=\"showEditRole(${r.id})\">编辑</button>\n"
    "          <button class=\"btn btn-danger btn-sm\" onclick=\"deleteItem('roles', ${r.id})\">删除</button>\n"
    "        </td></tr>`;\n"
    "      });\n"
    "      container.innerHTML = html + '</tbody></table>';\n"
    "    });\n"
    "  } else if(currentTab === 'groups') {\n"
    "    api('api/v1/groups' + query).then(res => {\n"
    "      const data = res.items;\n"
    "      state.groups.total = res.total;\n"
    "      allData.groups = data;\n"
    "      updatePaginationUI();\n"
    "      let html = '<table><thead><tr><th>ID</th><th>分组名称</th><th>父分组</th><th>描述</th><th>操作</th></tr></thead><tbody>';\n"
    "      data.forEach(g => {\n"
    "        html += `<tr><td>#${g.id}</td><td style=\"color:var(--text-bright);font-weight:600\">${g.name}</td><td>${g.parent_name||'-'}</td><td>${g.description||'-'}</td><td>\n"
    "          <button class=\"btn btn-outline btn-sm\" onclick=\"showEditGroup(${g.id})\">编辑</button>\n"
    "          <button class=\"btn btn-danger btn-sm\" onclick=\"deleteItem('groups', ${g.id})\">删除</button>\n"
    "        </td></tr>`;\n"
    "      });\n"
    "      container.innerHTML = html + '</tbody></table>';\n"
    "    });\n"
    "  } else if(currentTab === 'policies') {\n"
    "    api('api/v1/policies' + query).then(res => {\n"
    "      const data = res.items;\n"
    "      state.policies.total = res.total;\n"
    "      allData.policies = data;\n"
    "      updatePaginationUI();\n"
    "      document.getElementById('countPolicies').textContent = res.total;\n"
    "      let html = '<table><thead><tr><th>ID</th><th>名称</th><th>策略类型</th><th>效果</th><th>优先级</th><th>操作</th></tr></thead><tbody>';\n"
    "      data.forEach(p => {\n"
    "        html += `<tr><td>#${p.id}</td><td style=\"color:var(--text-bright);font-weight:600\">${p.name}</td><td>${p.strategy_name}</td><td><span class=\"status-pill ${p.effect === 1 ? 'status-active' : 'status-inactive'}\">${p.effect === 1 ? 'ALLOW' : 'DENY'}</span></td><td>${p.priority}</td><td>\n"
    "          <button class=\"btn btn-outline btn-sm\" onclick=\"showEditPolicy(${p.id})\">编辑</button>\n"
    "          <button class=\"btn btn-danger btn-sm\" onclick=\"deleteItem('policies', ${p.id})\">删除</button>\n"
    "        </td></tr>`;\n"
    "      });\n"
    "      container.innerHTML = html + '</tbody></table>';\n"
    "    });\n"
    "  } else if(currentTab === 'audit') {\n"
    "    api('api/v1/audit/logs').then(data => {\n"
    "      state.audit.total = data.length;\n"
    "      updatePaginationUI();\n"
    "      let html = '<table><thead><tr><th>时间</th><th>用户</th><th>决策</th><th>耗时</th><th>缓存</th><th>详情</th></tr></thead><tbody>';\n"
    "      data.reverse().slice(0, LIMIT).forEach(log => {\n"
    "        const date = new Date(log.timestamp_ms).toLocaleString();\n"
    "        const isAllow = log.decision === 'ALLOW';\n"
    "        html += `<tr>\n"
    "          <td style=\"font-size:12px\">${date}</td>\n"
    "          <td>#${log.user_id}</td>\n"
    "          <td><span class=\"status-pill\" style=\"background:${isAllow?'rgba(158,206,106,0.1)':'rgba(247,118,142,0.1)'};color:${isAllow?'var(--success)':'var(--error)'}\">${log.decision}</span></td>\n"
    "          <td style=\"font-family:monospace\">${log.duration_ms}ms</td>\n"
    "          <td>${log.cache_hit ? '⚡' : '-'}</td>\n"
    "          <td style=\"font-size:11px;color:var(--text-muted);max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap\" title=\"${log.trace}\">${log.trace}</td>\n"
    "        </tr>`;\n"
    "      });\n"
    "      container.innerHTML = html + '</tbody></table>';\n"
    "    });\n"
    "  } else if(currentTab === 'metrics') {\n"
    "    updatePaginationUI();\n"
    "    fetch('metrics').then(r => r.text()).then(m => {\n"
    "      container.innerHTML = `<pre style=\"padding:32px;background:var(--bg-dark);color:#79dac8;font-family:monospace;font-size:13px\">${m}</pre>`;\n"
    "      const match = m.match(/sso_perm_evals_total (\\d+)/);\n"
    "      if(match) document.getElementById('totalEvals').textContent = match[1];\n"
    "    });\n"
    "  }\n"
    "}\n"
    "\n"
    "async function deleteItem(type, id) {\n"
    "  if(!confirm('确定删除吗？')) return;\n"
    "  try {\n"
    "    await api(`/api/v1/${type}/${id}`, 'DELETE');\n"
    "    toast('删除成功'); loadData();\n"
    "  } catch(e) {}\n"
    "}\n"
    "\n"
    "async function showAssignments(userId) {\n"
    "  const u = allData.users.find(x => x.id === userId);\n"
    "  showModal(`管理 [${u.username}] 的角色与群组`, '设置该用户的权限边界与组织归属');\n"
    "  \n"
    "  const [roles, groups] = await Promise.all([api('api/v1/roles'), api('api/v1/groups')]);\n"
    "  \n"
    "  const userRoles = u.roles || [];\n"
    "  // For groups, we might need a separate API if not in user object. Assume u.groups exists for now or fetch.\n"
    "  // Assuming the backend returns groups in the user object like roles.\n"
    "  const userGroups = u.groups || [];\n"
    "\n"
    "  document.getElementById('modalContent').innerHTML = `\n"
    "    <div class=\"form-group\">\n"
    "      <label>分配角色</label>\n"
    "      <div style=\"display:flex;gap:10px;margin-bottom:10px\">\n"
    "        <select id=\"assignRoleSelect\" style=\"flex:1\">\n"
    "          ${roles.filter(r => !userRoles.some(ur => ur.id === r.id)).map(r => `<option value=\"${r.id}\">${r.name}</option>`).join('')}\n"
    "        </select>\n"
    "        <button class=\"btn btn-primary btn-sm\" onclick=\"doAssign(${userId}, 'role')\">增加</button>\n"
    "      </div>\n"
    "      <div id=\"userRolesList\" style=\"display:flex;flex-wrap:wrap;gap:8px\">\n"
    "        ${userRoles.map(r => `<span class=\"tag\">${r.name} <span style=\"cursor:pointer;margin-left:4px\" onclick=\"doUnassign(${userId}, 'role', ${r.id})\">×</span></span>`).join('')}\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"form-group\">\n"
    "      <label>所属群组</label>\n"
    "      <div style=\"display:flex;gap:10px;margin-bottom:10px\">\n"
    "        <select id=\"assignGroupSelect\" style=\"flex:1\">\n"
    "          ${groups.filter(g => !userGroups.some(ug => ug.id === g.id)).map(g => `<option value=\"${g.id}\">${g.name}</option>`).join('')}\n"
    "        </select>\n"
    "        <button class=\"btn btn-primary btn-sm\" onclick=\"doAssign(${userId}, 'group')\">加入</button>\n"
    "      </div>\n"
    "      <div id=\"userGroupsList\" style=\"display:flex;flex-wrap:wrap;gap:8px\">\n"
    "        ${userGroups.map(g => `<span class=\"tag\" style=\"background:rgba(187,154,247,0.1);color:var(--accent-light)\">${g.name} <span style=\"cursor:pointer;margin-left:4px\" onclick=\"doUnassign(${userId}, 'group', ${g.id})\">×</span></span>`).join('')}\n"
    "      </div>\n"
    "    </div>\n"
    "  `;\n"
    "  document.getElementById('confirmBtn').textContent = '完成并关闭';\n"
    "  document.getElementById('confirmBtn').onclick = closeModal;\n"
    "}\n"
    "\n"
    "async function doAssign(userId, type) {\n"
    "  const selectId = type === 'role' ? 'assignRoleSelect' : 'assignGroupSelect';\n"
    "  const id = document.getElementById(selectId).value;\n"
    "  if(!id) return;\n"
    "  \n"
    "  const path = type === 'role' ? `/api/v1/roles/${id}/assign` : `/api/v1/groups/${id}/members`;\n"
    "  const body = type === 'role' ? {user_id: userId} : {user_id: userId};\n"
    "  \n"
    "  await api(path, 'POST', body);\n"
    "  toast('分配成功');\n"
    "  // Refresh users to get latest assignments in allData.users\n"
    "  await api('api/v1/users').then(data => { allData.users = data; });\n"
    "  showAssignments(userId);\n"
    "}\n"
    "\n"
    "async function doUnassign(userId, type, id) {\n"
    "  if(!confirm('确定移除吗？')) return;\n"
    "  const path = type === 'role' ? `/api/v1/roles/${id}/unassign` : `/api/v1/groups/${id}/members/${userId}`;\n"
    "  await api(path, type === 'role' ? 'POST' : 'DELETE', type === 'role' ? {user_id: userId} : null);\n"
    "  toast('已移除');\n"
    "  await api('api/v1/users').then(data => { allData.users = data; });\n"
    "  showAssignments(userId);\n"
    "}\n"
    "\n"
    "function showEditUser(id) {\n"
    "  const u = id ? allData.users.find(x => x.id === id) : {username:'', email:'', display_name:'', phone:'', status:1};\n"
    "  showModal(id ? '编辑用户' : '新增用户', '管理 SSO 账号');\n"
    "  document.getElementById('modalContent').innerHTML = `\n"
    "    <div class=\"form-group\"><label>用户名</label><input id=\"f_user\" value=\"${u.username}\" ${id?'readonly':''}></div>\n"
    "    ${!id ? '<div class=\"form-group\"><label>初始密码</label><input type=\"password\" id=\"f_pass\"></div>' : ''}\n"
    "    <div class=\"form-group\"><label>显示名称</label><input id=\"f_display\" value=\"${u.display_name||''}\"></div>\n"
    "    <div class=\"form-group\"><label>邮箱地址</label><input id=\"f_email\" value=\"${u.email||''}\"></div>\n"
    "    <div class=\"form-group\"><label>手机号</label><input id=\"f_phone\" value=\"${u.phone||''}\"></div>\n"
    "    <div class=\"form-group\"><label>状态</label>\n"
    "      <select id=\"f_status\">\n"
    "        <option value=\"1\" ${u.status==1?'selected':''}>正常</option>\n"
    "        <option value=\"0\" ${u.status==0?'selected':''}>禁用</option>\n"
    "        <option value=\"2\" ${u.status==2?'selected':''}>锁定</option>\n"
    "      </select>\n"
    "    </div>\n"
    "  `;\n"
    "  document.getElementById('confirmBtn').onclick = async () => {\n"
    "    const payload = {\n"
    "      username: document.getElementById('f_user').value,\n"
    "      email: document.getElementById('f_email').value,\n"
    "      display_name: document.getElementById('f_display').value,\n"
    "      phone: document.getElementById('f_phone').value,\n"
    "      status: parseInt(document.getElementById('f_status').value)\n"
    "    };\n"
    "    if(!id) {\n"
    "      if(!payload.username || !document.getElementById('f_pass').value) return toast('请填全信息', 'error');\n"
    "      payload.password = document.getElementById('f_pass').value;\n"
    "    }\n"
    "    await api(id ? `/api/v1/users/${id}` : 'api/v1/users', id ? 'PUT' : 'POST', payload);\n"
    "    toast('保存成功'); closeModal(); loadData();\n"
    "  };\n"
    "}\n"
    "\n"
    "function showEditRole(id) {\n"
    "  const r = id ? allData.roles.find(x => x.id === id) : {name:'', description:'', parent_role_id:0, status:1};\n"
    "  showModal(id ? '编辑角色' : '新增角色', '定义权限角色与层级');\n"
    "  document.getElementById('modalContent').innerHTML = `\n"
    "    <div class=\"form-group\"><label>角色名称</label><input id=\"r_name\" value=\"${r.name}\"></div>\n"
    "    <div class=\"form-group\"><label>描述</label><input id=\"r_desc\" value=\"${r.description||''}\"></div>\n"
    "    <div class=\"form-group\"><label>状态</label>\n"
    "      <select id=\"r_status\"><option value=\"1\" ${r.status==1?'selected':''}>激活</option><option value=\"0\" ${r.status==0?'selected':''}>禁用</option></select>\n"
    "    </div>\n"
    "  `;\n"
    "  document.getElementById('confirmBtn').onclick = async () => {\n"
    "    const payload = {\n"
    "      name: document.getElementById('r_name').value,\n"
    "      description: document.getElementById('r_desc').value,\n"
    "      status: parseInt(document.getElementById('r_status').value),\n"
    "      parent_role_id: r.parent_role_id || 0\n"
    "    };\n"
    "    await api(id ? `/api/v1/roles/${id}` : 'api/v1/roles', id ? 'PUT' : 'POST', payload);\n"
    "    toast('保存成功'); closeModal(); loadData();\n"
    "  };\n"
    "}\n"
    "\n"
    "function showEditGroup(id) {\n"
    "  const g = id ? allData.groups.find(x => x.id === id) : {name:'', description:'', parent_group_id:0, status:1};\n"
    "  showModal(id ? '编辑群组' : '新增群组', '管理组织架构单元');\n"
    "  document.getElementById('modalContent').innerHTML = `\n"
    "    <div class=\"form-group\"><label>群组名称</label><input id=\"g_name\" value=\"${g.name}\"></div>\n"
    "    <div class=\"form-group\"><label>描述</label><input id=\"g_desc\" value=\"${g.description||''}\"></div>\n"
    "    <div class=\"form-group\"><label>状态</label>\n"
    "      <select id=\"g_status\"><option value=\"1\" ${g.status==1?'selected':''}>激活</option><option value=\"0\" ${g.status==0?'selected':''}>禁用</option></select>\n"
    "    </div>\n"
    "  `;\n"
    "  document.getElementById('confirmBtn').onclick = async () => {\n"
    "    const payload = {\n"
    "      name: document.getElementById('g_name').value,\n"
    "      description: document.getElementById('g_desc').value,\n"
    "      status: parseInt(document.getElementById('g_status').value),\n"
    "      parent_group_id: g.parent_group_id || 0\n"
    "    };\n"
    "    await api(id ? `/api/v1/groups/${id}` : 'api/v1/groups', id ? 'PUT' : 'POST', payload);\n"
    "    toast('保存成功'); closeModal(); loadData();\n"
    "  };\n"
    "}\n"
    "\n"
    "function handleAdd() {\n"
    "  if(currentTab === 'users') showEditUser(0);\n"
    "  else if(currentTab === 'roles') showEditRole(0);\n"
    "  else if(currentTab === 'groups') showEditGroup(0);\n"
    "  else if(currentTab === 'policies') showEditPolicy(0);\n"
    "}\n"
    "\n"
    "function showEditPolicy(id) {\n"
    "  const p = id ? allData.policies.find(x => x.id === id) : {name:'', strategy_type:1, effect:1, priority:50, rules:'{}'};\n"
    "  showModal(id ? '配置策略' : '新增策略', '定义访问控制规则');\n"
    "  document.getElementById('modalContent').innerHTML = `\n"
    "    <div class=\"form-group\"><label>策略名称</label><input id=\"p_name\" value=\"${p.name}\"></div>\n"
    "    <div style=\"display:flex;gap:10px\">\n"
    "      <div class=\"form-group\" style=\"flex:1\"><label>策略引擎类型</label>\n"
    "        <select id=\"p_type\" onchange=\"renderRuleBuilder(parseInt(this.value))\">\n"
    "          <option value=\"1\" ${p.strategy_type==1?'selected':''}>功能权限 (FUNC)</option>\n"
    "          <option value=\"2\" ${p.strategy_type==2?'selected':''}>API 权限 (API)</option>\n"
    "          <option value=\"4\" ${p.strategy_type==4?'selected':''}>角色权限 (RBAC)</option>\n"
    "          <option value=\"3\" ${p.strategy_type==3?'selected':''}>数据权限 (DATA)</option>\n"
    "          <option value=\"6\" ${p.strategy_type==6?'selected':''}>属性权限 (ABAC)</option>\n"
    "        </select>\n"
    "      </div>\n"
    "      <div class=\"form-group\" style=\"width:120px\"><label>效果</label>\n"
    "        <select id=\"p_effect\"><option value=\"1\" ${p.effect?'selected':''}>ALLOW</option><option value=\"0\" ${!p.effect?'selected':''}>DENY</option></select>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div id=\"ruleBuilder\" class=\"rule-builder\"></div>\n"
    "  `;\n"
    "  \n"
    "  try {\n"
    "    const r = JSON.parse(p.rules);\n"
    "    if(p.strategy_type==1) policyRules = (r.functions||[]).map(x=>({k:x.code, v:x.effect||'allow'}));\n"
    "    else if(p.strategy_type==2) policyRules = (r.endpoints||[]).map(x=>({k:x.path, v:x.method||'GET'}));\n"
    "    else if(p.strategy_type==4) policyRules = (r.roles||[]).map(x=>({k:x.name, v:x.effect||'allow'}));\n"
    "    else if(p.strategy_type==6) policyRules = (r.conditions||[]).map(x=>({k:x.attr, v:x.value, op:x.op, src:x.source}));\n"
    "    else policyRules = [];\n"
    "  } catch(e) { policyRules = []; }\n"
    "  \n"
    "  renderRuleBuilder(p.strategy_type);\n"
    "\n"
    "  document.getElementById('confirmBtn').onclick = async () => {\n"
    "    const type = parseInt(document.getElementById('p_type').value);\n"
    "    let rules = {};\n"
    "    if(type==1) rules = {functions: policyRules.map(x=>({code:x.k, effect:x.v}))};\n"
    "    else if(type==2) rules = {endpoints: policyRules.map(x=>({path:x.k, method:x.v}))};\n"
    "    else if(type==4) rules = {roles: policyRules.map(x=>({name:x.k, effect:x.v}))};\n"
    "    else if(type==6) rules = {conditions: policyRules.map(x=>({source:x.src, attr:x.k, op:x.op, value:x.v}))};\n"
    "    \n"
    "    const payload = { name:document.getElementById('p_name').value, strategy_type:type, effect:parseInt(document.getElementById('p_effect').value), priority:50, rules:JSON.stringify(rules), status:1 };\n"
    "    await api(id ? `/api/v1/policies/${id}` : 'api/v1/policies', id ? 'PUT' : 'POST', payload);\n"
    "    toast('保存成功'); closeModal(); loadData();\n"
    "  };\n"
    "}\n"
    "\n"
    "function renderRuleBuilder(type) {\n"
    "  const container = document.getElementById('ruleBuilder');\n"
    "  container.innerHTML = '<div id=\"rulesList\"></div><button class=\"btn btn-outline btn-sm\" onclick=\"addRuleItem('+type+')\">+ 添加规则项</button>';\n"
    "  refreshRulesList(type);\n"
    "}\n"
    "\n"
    "function addRuleItem(t) {\n"
    "  if(t==6) policyRules.push({k:'', v:'', op:'eq', src:'subject'});\n"
    "  else policyRules.push({k:'', v:t==2?'GET':'allow'});\n"
    "  refreshRulesList(t);\n"
    "}\n"
    "\n"
    "function refreshRulesList(type) {\n"
    "  const container = document.getElementById('rulesList');\n"
    "  container.innerHTML = policyRules.map((r, i) => {\n"
    "    if(type == 6) { // ABAC\n"
    "      return `<div class=\"rule-item\">\n"
    "        <select style=\"flex:1\" onchange=\"policyRules[${i}].src=this.value\"><option value=\"subject\" ${r.src=='subject'?'selected':''}>主体</option><option value=\"resource\" ${r.src=='resource'?'selected':''}>资源</option></select>\n"
    "        <input style=\"flex:1\" placeholder=\"属性\" value=\"${r.k}\" oninput=\"policyRules[${i}].k=this.value\">\n"
    "        <select style=\"flex:0.8\" onchange=\"policyRules[${i}].op=this.value\"><option value=\"eq\" ${r.op=='eq'?'selected':''}>=</option><option value=\"gt\" ${r.op=='gt'?'selected':''}>></option></select>\n"
    "        <input style=\"flex:1\" placeholder=\"值\" value=\"${r.v}\" oninput=\"policyRules[${i}].v=this.value\">\n"
    "        <button class=\"btn btn-danger btn-sm\" onclick=\"policyRules.splice(${i},1);refreshRulesList(${type})\">×</button>\n"
    "      </div>`;\n"
    "    }\n"
    "    return `<div class=\"rule-item\">\n"
    "      <input style=\"flex:2\" placeholder=\"${type==2?'API 路径':'标识'}\" value=\"${r.k}\" oninput=\"policyRules[${i}].k=this.value\">\n"
    "      <input style=\"flex:1\" placeholder=\"${type==2?'HTTP 方法':'效果'}\" value=\"${r.v}\" oninput=\"policyRules[${i}].v=this.value\">\n"
    "      <button class=\"btn btn-danger btn-sm\" onclick=\"policyRules.splice(${i},1);refreshRulesList(${type})\">×</button>\n"
    "    </div>`;\n"
    "  }).join('');\n"
    "}\n"
    "\n"
    "function showChangePass() {\n"
    "  showModal('修改登录密码', '设置一个新的安全密码');\n"
    "  document.getElementById('modalContent').innerHTML = `\n"
    "    <div class=\"form-group\"><label>新密码</label><input type=\"password\" id=\"p_new\" placeholder=\"最少6位字符\"></div>\n"
    "    <div class=\"form-group\"><label>确认密码</label><input type=\"password\" id=\"p_conf\" placeholder=\"再次输入新密码\"></div>\n"
    "  `;\n"
    "  document.getElementById('confirmBtn').onclick = async () => {\n"
    "    const p1 = document.getElementById('p_new').value;\n"
    "    const p2 = document.getElementById('p_conf').value;\n"
    "    if(p1.length < 6) return toast('密码太短', 'error');\n"
    "    if(p1 !== p2) return toast('两次输入不一致', 'error');\n"
    "    await api('api/v1/auth/password', 'POST', { password: p1 });\n"
    "    toast('密码修改成功'); closeModal();\n"
    "  };\n"
    "}\n"
    "\n"
    "function logout() { localStorage.removeItem(TOKEN_KEY); window.location.href = './'; }\n"
    "function closeModal() { document.getElementById('modalOverlay').classList.remove('active'); }\n"
    "function showModal(title, sub) { document.getElementById('modalTitle').textContent=title; document.getElementById('modalSub').textContent=sub; document.getElementById('modalOverlay').classList.add('active'); }\n"
    "\n"
    "// Init\n"
    "let token = localStorage.getItem(TOKEN_KEY);\n"
    "if(window.location.hash) {\n"
    "  token = decodeURIComponent(window.location.hash.substring(1));\n"
    "  localStorage.setItem(TOKEN_KEY, token);\n"
    "  window.location.hash = '';\n"
    "}\n"
    "if(token) {\n"
    "  api('api/v1/auth/me').then(async d => {\n"
    "    // Robust check: fetch full user details to confirm roles\n"
    "    const u = await api(`api/v1/users/${d.id}`);\n"
    "    const isAdmin = (u.roles || []).some(r => r.name === 'admin');\n"
    "    \n"
    "    if(!isAdmin) {\n"
    "      alert('权限不足：仅管理员可以访问此页面');\n"
    "      logout();\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    document.getElementById('adminName').textContent = d.display_name || d.username;\n"
    "    document.getElementById('avatar').textContent = (d.display_name || d.username)[0].toUpperCase();\n"
    "    document.body.style.display = 'flex'; // Unlock UI\n"
    "    loadData();\n"
    "  }).catch(() => { logout(); });\n"
    "} else { window.location.href = './'; }\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;

#endif /* SSO_ADMIN_PAGE_H */
