/*
 * login_page.h — Built-in login page HTML (auto-generated)
 */
#ifndef SSO_LOGIN_PAGE_H
#define SSO_LOGIN_PAGE_H

static const char LOGIN_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>SSO 统一身份认证</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    ":root{\n"
    "  --bg-dark:#0f111a;\n"
    "  --bg-card:#161925;\n"
    "  --bg-input:#1f2335;\n"
    "  --accent:#7aa2f7;\n"
    "  --accent-glow:rgba(122,162,247,0.3);\n"
    "  --text-main:#a9b1d6;\n"
    "  --text-bright:#c0caf5;\n"
    "  --text-muted:#565f89;\n"
    "  --border:#292e42;\n"
    "  --error:#f7768e;\n"
    "  --radius:12px;\n"
    "}\n"
    "body{\n"
    "  font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;\n"
    "  background:var(--bg-dark);\n"
    "  color:var(--text-main);\n"
    "  min-height:100vh;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  overflow:hidden;\n"
    "  position:relative;\n"
    "}\n"
    "body::before{\n"
    "  content:'';\n"
    "  position:absolute;\n"
    "  width:1000px;height:1000px;\n"
    "  background:radial-gradient(circle, rgba(122,162,247,0.05) 0%, transparent 70%);\n"
    "  top:-200px;right:-200px;\n"
    "  pointer-events:none;\n"
    "}\n"
    "body::after{\n"
    "  content:'';\n"
    "  position:absolute;\n"
    "  width:800px;height:800px;\n"
    "  background:radial-gradient(circle, rgba(187,154,247,0.03) 0%, transparent 70%);\n"
    "  bottom:-200px;left:-200px;\n"
    "  pointer-events:none;\n"
    "}\n"
    ".login-card{\n"
    "  width:400px;\n"
    "  background:var(--bg-card);\n"
    "  border:1px solid var(--border);\n"
    "  border-radius:24px;\n"
    "  padding:48px;\n"
    "  box-shadow:0 20px 50px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.02);\n"
    "  z-index:10;\n"
    "  position:relative;\n"
    "}\n"
    ".logo-area{\n"
    "  text-align:center;\n"
    "  margin-bottom:40px;\n"
    "}\n"
    ".logo-icon{\n"
    "  width:48px;height:48px;\n"
    "  background:linear-gradient(135deg, #7aa2f7, #bb9af7);\n"
    "  border-radius:12px;\n"
    "  display:inline-flex;align-items:center;justify-content:center;\n"
    "  color:#fff;font-weight:bold;font-size:24px;\n"
    "  margin-bottom:16px;\n"
    "  box-shadow:0 0 20px rgba(122,162,247,0.4);\n"
    "}\n"
    "h1{font-size:24px;color:var(--text-bright);font-weight:700;letter-spacing:-0.5px}\n"
    ".subtitle{font-size:14px;color:var(--text-muted);margin-top:8px}\n"
    "\n"
    ".tabs{\n"
    "  display:flex;background:var(--bg-dark);padding:4px;border-radius:10px;\n"
    "  margin-bottom:32px;border:1px solid var(--border);\n"
    "}\n"
    ".tab{\n"
    "  flex:1;text-align:center;padding:8px;font-size:13px;cursor:pointer;\n"
    "  border-radius:8px;transition:all 0.2s;color:var(--text-muted);\n"
    "}\n"
    ".tab.active{background:var(--bg-input);color:var(--accent);font-weight:600}\n"
    "\n"
    ".form-group{margin-bottom:20px}\n"
    ".form-group label{display:block;font-size:12px;color:var(--text-muted);margin-bottom:8px;font-weight:500;text-transform:uppercase;letter-spacing:0.5px}\n"
    "input{\n"
    "  width:100%;background:var(--bg-input);border:1px solid var(--border);\n"
    "  padding:14px 16px;border-radius:var(--radius);color:var(--text-bright);\n"
    "  font-size:15px;transition:all 0.2s;outline:none;\n"
    "}\n"
    "input:focus{border-color:var(--accent);box-shadow:0 0 0 4px var(--accent-glow)}\n"
    "input::placeholder{color:var(--text-muted)}\n"
    "\n"
    ".btn{\n"
    "  width:100%;padding:14px;border-radius:var(--radius);border:none;\n"
    "  font-size:15px;font-weight:600;cursor:pointer;transition:all 0.2s;\n"
    "  display:flex;align-items:center;justify-content:center;gap:10px;\n"
    "}\n"
    ".btn-primary{background:linear-gradient(135deg, #7aa2f7, #bb9af7);color:#fff;margin-top:10px}\n"
    ".btn-primary:hover{opacity:0.9;transform:translateY(-1px)}\n"
    ".btn-primary:active{transform:translateY(0)}\n"
    "\n"
    ".sms-input-row{display:flex;gap:10px}\n"
    ".btn-sms{width:auto;white-space:nowrap;background:var(--bg-input);color:var(--text-bright);border:1px solid var(--border);font-size:13px}\n"
    ".btn-sms:disabled{color:var(--text-muted);cursor:not-allowed}\n"
    "\n"
    ".error-bar{\n"
    "  background:rgba(247,118,142,0.1);color:var(--error);\n"
    "  padding:12px;border-radius:8px;font-size:13px;margin-bottom:20px;\n"
    "  display:none;border-left:4px solid var(--error);\n"
    "}\n"
    ".error-bar.visible{display:block}\n"
    "\n"
    ".switch-footer{text-align:center;margin-top:32px;font-size:13px;color:var(--text-muted)}\n"
    ".switch-footer span{color:var(--accent);cursor:pointer;font-weight:500}\n"
    ".switch-footer span:hover{text-decoration:underline}\n"
    "\n"
    "/* Success UI */\n"
    ".success-view{display:none;text-align:center}\n"
    ".token-box{\n"
    "  background:var(--bg-dark);border:1px solid var(--border);\n"
    "  border-radius:12px;padding:16px;margin:24px 0;\n"
    "  font-family:monospace;font-size:11px;word-break:break-all;\n"
    "  color:var(--accent);max-height:100px;overflow-y:auto;text-align:left;\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div class=\"login-card\" id=\"card\">\n"
    "  <!-- Login State -->\n"
    "  <div id=\"loginView\">\n"
    "    <div class=\"logo-area\">\n"
    "      <div class=\"logo-icon\">S</div>\n"
    "      <h1>SSO 统一认证</h1>\n"
    "      <div class=\"subtitle\">Securely access your services</div>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"tabs\">\n"
    "      <div class=\"tab active\" onclick=\"switchTab('pass')\">密码登录</div>\n"
    "      <div class=\"tab\" onclick=\"switchTab('sms')\">验证码登录</div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"errorBar\" class=\"error-bar\"></div>\n"
    "\n"
    "    <form id=\"passForm\">\n"
    "      <div class=\"form-group\">\n"
    "        <label>用户名</label>\n"
    "        <input type=\"text\" id=\"username\" placeholder=\"输入用户名\" autocomplete=\"username\">\n"
    "      </div>\n"
    "      <div class=\"form-group\">\n"
    "        <label>密码</label>\n"
    "        <input type=\"password\" id=\"password\" placeholder=\"输入密码\" autocomplete=\"current-password\">\n"
    "      </div>\n"
    "      <button type=\"submit\" class=\"btn btn-primary\">进入系统</button>\n"
    "    </form>\n"
    "\n"
    "    <form id=\"smsForm\" style=\"display:none\">\n"
    "      <div class=\"form-group\">\n"
    "        <label>手机号</label>\n"
    "        <div class=\"sms-input-row\">\n"
    "          <input type=\"tel\" id=\"phone\" placeholder=\"138xxxx8888\">\n"
    "          <button type=\"button\" class=\"btn btn-sms\" id=\"smsBtn\">获取验证码</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"form-group\">\n"
    "        <label>验证码</label>\n"
    "        <input type=\"text\" id=\"code\" placeholder=\"6位数字\" maxlength=\"6\">\n"
    "      </div>\n"
    "      <button type=\"submit\" class=\"btn btn-primary\">登录 / 快速注册</button>\n"
    "    </form>\n"
    "\n"
    "    <div class=\"switch-footer\">\n"
    "      还没有账号？<span onclick=\"toggleMode('reg')\">立即注册</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Register State -->\n"
    "  <div id=\"regView\" style=\"display:none\">\n"
    "    <div class=\"logo-area\">\n"
    "      <div class=\"logo-icon\">S</div>\n"
    "      <h1>创建账号</h1>\n"
    "      <div class=\"subtitle\">Join our secure platform</div>\n"
    "    </div>\n"
    "    <div class=\"form-group\">\n"
    "      <label>用户名</label>\n"
    "      <input type=\"text\" id=\"r_user\" placeholder=\"字母、数字组合\">\n"
    "    </div>\n"
    "    <div class=\"form-group\">\n"
    "      <label>显示名称</label>\n"
    "      <input type=\"text\" id=\"r_name\" placeholder=\"您的姓名或昵称\">\n"
    "    </div>\n"
    "    <div class=\"form-group\">\n"
    "      <label>设置密码</label>\n"
    "      <input type=\"password\" id=\"r_pass\" placeholder=\"最少6位字符\">\n"
    "    </div>\n"
    "    <button class=\"btn btn-primary\" onclick=\"doRegister()\">创建我的账号</button>\n"
    "    <div class=\"switch-footer\">\n"
    "      已有账号？<span onclick=\"toggleMode('login')\">返回登录</span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Success State -->\n"
    "  <div id=\"successView\" class=\"success-view\">\n"
    "    <div class=\"logo-area\">\n"
    "      <div style=\"font-size:48px;margin-bottom:16px\">✅</div>\n"
    "      <h1>认证成功</h1>\n"
    "      <div class=\"subtitle\">您已获得系统访问权限</div>\n"
    "    </div>\n"
    "    <div class=\"token-box\" id=\"tokenDisplay\"></div>\n"
    "    <div style=\"display:flex;gap:10px\">\n"
    "      <a href=\"admin\" id=\"adminLink\" class=\"btn btn-primary\" style=\"flex:1;text-decoration:none\">管理后台</a>\n"
    "      <button class=\"btn btn-sms\" onclick=\"location.reload()\">重新登录</button>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div id=\"toastContainer\" style=\"position:fixed;top:20px;right:20px;z-index:2000\"></div>\n"
    "\n"
    "<script>\n"
    "let mode = 'pass';\n"
    "const errorBar = document.getElementById('errorBar');\n"
    "\n"
    "function toast(msg, type='success') {\n"
    "  const container = document.getElementById('toastContainer');\n"
    "  const t = document.createElement('div');\n"
    "  t.style.padding = '12px 24px';\n"
    "  t.style.borderRadius = '8px';\n"
    "  t.style.background = 'var(--bg-card)';\n"
    "  t.style.color = '#fff';\n"
    "  t.style.border = '1px solid var(--border)';\n"
    "  t.style.boxShadow = '0 10px 30px rgba(0,0,0,0.5)';\n"
    "  t.style.marginBottom = '10px';\n"
    "  t.style.borderLeft = `4px solid var(--${type === 'success' ? 'success' : 'error'})`;\n"
    "  t.textContent = msg;\n"
    "  t.style.transition = 'opacity 0.3s';\n"
    "  container.appendChild(t);\n"
    "  setTimeout(() => { t.style.opacity = '0'; setTimeout(() => t.remove(), 300); }, 3000);\n"
    "}\n"
    "\n"
    "function switchTab(t) {\n"
    "  mode = t;\n"
    "  document.querySelectorAll('.tab').forEach((el, i) => el.classList.toggle('active', (t==='pass' && i===0) || (t==='sms' && i===1)));\n"
    "  document.getElementById('passForm').style.display = t === 'pass' ? 'block' : 'none';\n"
    "  document.getElementById('smsForm').style.display = t === 'sms' ? 'block' : 'none';\n"
    "  errorBar.className = 'error-bar';\n"
    "}\n"
    "\n"
    "function toggleMode(m) {\n"
    "  document.getElementById('loginView').style.display = m === 'reg' ? 'none' : 'block';\n"
    "  document.getElementById('regView').style.display = m === 'reg' ? 'block' : 'none';\n"
    "}\n"
    "\n"
    "function showError(m) {\n"
    "  errorBar.textContent = m;\n"
    "  errorBar.className = 'error-bar visible';\n"
    "}\n"
    "\n"
    "// APIs\n"
    "async function post(url, data) {\n"
    "  const r = await fetch(url, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data)});\n"
    "  const json = await r.json();\n"
    "  if(!r.ok) throw new Error(json.error || '请求失败');\n"
    "  return json;\n"
    "}\n"
    "\n"
    "document.getElementById('passForm').onsubmit = async (e) => {\n"
    "  e.preventDefault();\n"
    "  try {\n"
    "    const res = await post('api/v1/auth/login', {username:document.getElementById('username').value, password:document.getElementById('password').value});\n"
    "    onSuccess(res);\n"
    "  } catch(e) { showError(e.message); }\n"
    "};\n"
    "\n"
    "document.getElementById('smsBtn').onclick = async () => {\n"
    "  const phone = document.getElementById('phone').value;\n"
    "  if(phone.length < 11) return showError('请输入正确的手机号');\n"
    "  try {\n"
    "    await post('api/v1/auth/send_sms', {phone});\n"
    "    let s = 60;\n"
    "    const btn = document.getElementById('smsBtn');\n"
    "    btn.disabled = true;\n"
    "    const timer = setInterval(() => {\n"
    "      btn.textContent = `${--s}s`;\n"
    "      if(s <= 0) { clearInterval(timer); btn.disabled = false; btn.textContent = '获取验证码'; }\n"
    "    }, 1000);\n"
    "  } catch(e) { showError(e.message); }\n"
    "};\n"
    "\n"
    "document.getElementById('smsForm').onsubmit = async (e) => {\n"
    "  e.preventDefault();\n"
    "  try {\n"
    "    const res = await post('api/v1/auth/login_by_sms', {phone:document.getElementById('phone').value, code:document.getElementById('code').value});\n"
    "    onSuccess(res);\n"
    "  } catch(e) { showError(e.message); }\n"
    "};\n"
    "\n"
    "async function doRegister() {\n"
    "  try {\n"
    "    const res = await post('api/v1/auth/register', {\n"
    "      username: document.getElementById('r_user').value, \n"
    "      password: document.getElementById('r_pass').value, \n"
    "      display_name: document.getElementById('r_name').value\n"
    "    });\n"
    "    toast('注册成功，请登录');\n"
    "    toggleMode('login');\n"
    "    document.getElementById('username').value = res.username;\n"
    "    document.getElementById('password').focus();\n"
    "  } catch(e) { showError(e.message); }\n"
    "}\n"
    "\n"
    "function onSuccess(res) {\n"
    "  localStorage.setItem('sso_token', res.access_token);\n"
    "  // Set cookie for Nginx auth_request\n"
    "  document.cookie = `sso_token=${res.access_token}; path=/; max-age=3600; SameSite=Lax`;\n"
    "\n"
    "  const params = new URLSearchParams(window.location.search);\n"
    "  const redirect = params.get('redirect');\n"
    "  if (redirect) {\n"
    "    window.location.href = redirect;\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  document.getElementById('loginView').style.display = 'none';\n"
    "  document.getElementById('successView').style.display = 'block';\n"
    "  document.getElementById('tokenDisplay').textContent = res.access_token;\n"
    "  document.getElementById('adminLink').href = `admin#${encodeURIComponent(res.access_token)}`;\n"
    "}\n"
    "\n"
    "// Redirect if already has token\n"
    "const t = localStorage.getItem('sso_token');\n"
    "if(t) {\n"
    "  fetch('api/v1/auth/verify', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:t})})\n"
    "    .then(r => r.json()).then(d => { if(d.valid) onSuccess({token:t}); });\n"
    "}\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;

#endif /* SSO_LOGIN_PAGE_H */
