/*
 * login_page.h — Built-in login page HTML (auto-generated)
 */
#ifndef SSO_LOGIN_PAGE_H
#define SSO_LOGIN_PAGE_H

static const char LOGIN_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>SSO 统一认证</title>\n"
    "<style>\n"
    "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
    ":root{\n"
    "  --bg-primary:#0f1117;\n"
    "  --bg-secondary:#1a1d27;\n"
    "  --bg-tertiary:#242836;\n"
    "  --bg-input:#2a2e3d;\n"
    "  --border-color:#363b4d;\n"
    "  --border-focus:#5b6abf;\n"
    "  --text-primary:#e4e6ef;\n"
    "  --text-secondary:#9498ad;\n"
    "  --text-muted:#6b6f85;\n"
    "  --accent:#5b6abf;\n"
    "  --accent-hover:#6d7ad0;\n"
    "  --accent-active:#4f5aad;\n"
    "  --success:#3ecf8e;\n"
    "  --success-bg:rgba(62,207,142,.1);\n"
    "  --error:#ef5f5f;\n"
    "  --error-bg:rgba(239,95,95,.1);\n"
    "  --radius-sm:6px;\n"
    "  --radius-md:10px;\n"
    "  --radius-lg:14px;\n"
    "  --shadow-sm:0 1px 3px rgba(0,0,0,.3);\n"
    "  --shadow-md:0 4px 16px rgba(0,0,0,.4);\n"
    "  --shadow-lg:0 8px 32px rgba(0,0,0,.5);\n"
    "  --space-1:4px;\n"
    "  --space-2:8px;\n"
    "  --space-3:12px;\n"
    "  --space-4:16px;\n"
    "  --space-5:20px;\n"
    "  --space-6:24px;\n"
    "  --space-8:32px;\n"
    "  --space-10:40px;\n"
    "  --font-sans:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Noto Sans SC\",\"PingFang SC\",\"Hiragino Sans GB\",\"Microsoft YaHei\",sans-serif;\n"
    "  --font-mono:\"SF Mono\",\"Fira Code\",\"Cascadia Code\",monospace;\n"
    "  --text-xs:.75rem;\n"
    "  --text-sm:.8125rem;\n"
    "  --text-base:.9375rem;\n"
    "  --text-lg:1.125rem;\n"
    "  --text-xl:1.5rem;\n"
    "  --text-2xl:1.875rem;\n"
    "  --leading-normal:1.6;\n"
    "}\n"
    "html{font-size:16px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;height:100%}\n"
    "body{\n"
    "  font-family:var(--font-sans);\n"
    "  background:var(--bg-primary);\n"
    "  color:var(--text-primary);\n"
    "  line-height:var(--leading-normal);\n"
    "  min-height:100%;\n"
    "  display:flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  padding:var(--space-4);\n"
    "  position:relative;\n"
    "  overflow:hidden;\n"
    "}\n"
    "body::before{\n"
    "  content:'';\n"
    "  position:fixed;\n"
    "  inset:0;\n"
    "  background:\n"
    "    radial-gradient(ellipse 80% 60% at 20% 80%,rgba(91,106,191,.18),transparent),\n"
    "    radial-gradient(ellipse 60% 50% at 80% 20%,rgba(62,207,142,.08),transparent),\n"
    "    radial-gradient(ellipse 50% 40% at 50% 50%,rgba(91,106,191,.06),transparent);\n"
    "  pointer-events:none;\n"
    "  z-index:0;\n"
    "}\n"
    "body::after{\n"
    "  content:'';\n"
    "  position:fixed;\n"
    "  inset:0;\n"
    "  background-image:url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%235b6abf' fill-opacity='.03'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\");\n"
    "  pointer-events:none;\n"
    "  z-index:0;\n"
    "}\n"
    ".bg-orb{\n"
    "  position:fixed;\n"
    "  border-radius:50%;\n"
    "  filter:blur(80px);\n"
    "  pointer-events:none;\n"
    "  z-index:0;\n"
    "  animation:orbFloat 20s ease-in-out infinite;\n"
    "}\n"
    ".bg-orb:nth-child(1){\n"
    "  width:500px;height:500px;\n"
    "  background:rgba(91,106,191,.12);\n"
    "  top:-10%;left:-10%;\n"
    "  animation-delay:0s;\n"
    "}\n"
    ".bg-orb:nth-child(2){\n"
    "  width:400px;height:400px;\n"
    "  background:rgba(62,207,142,.08);\n"
    "  bottom:-15%;right:-10%;\n"
    "  animation-delay:-7s;\n"
    "}\n"
    ".bg-orb:nth-child(3){\n"
    "  width:300px;height:300px;\n"
    "  background:rgba(91,106,191,.1);\n"
    "  top:40%;left:60%;\n"
    "  animation-delay:-14s;\n"
    "}\n"
    "@keyframes orbFloat{\n"
    "  0%,100%{transform:translate(0,0) scale(1)}\n"
    "  25%{transform:translate(60px,-40px) scale(1.1)}\n"
    "  50%{transform:translate(-30px,60px) scale(.95)}\n"
    "  75%{transform:translate(40px,30px) scale(1.05)}\n"
    "}\n"
    ".container{\n"
    "  width:100%;\n"
    "  max-width:420px;\n"
    "  position:relative;\n"
    "  z-index:1;\n"
    "}\n"
    ".card{\n"
    "  background:var(--bg-secondary);\n"
    "  border:1px solid var(--border-color);\n"
    "  border-radius:var(--radius-lg);\n"
    "  box-shadow:var(--shadow-lg),0 0 60px rgba(91,106,191,.06);\n"
    "  padding:var(--space-8);\n"
    "}\n"
    ".header{\n"
    "  text-align:center;\n"
    "  margin-bottom:var(--space-8);\n"
    "}\n"
    ".header h1{\n"
    "  font-size:var(--text-2xl);\n"
    "  font-weight:700;\n"
    "  letter-spacing:-.02em;\n"
    "  color:var(--text-primary);\n"
    "  margin-bottom:var(--space-2);\n"
    "}\n"
    ".header p{\n"
    "  font-size:var(--text-sm);\n"
    "  color:var(--text-secondary);\n"
    "}\n"
    ".form-group{\n"
    "  margin-bottom:var(--space-5);\n"
    "}\n"
    ".form-group label{\n"
    "  display:block;\n"
    "  font-size:var(--text-sm);\n"
    "  font-weight:500;\n"
    "  color:var(--text-secondary);\n"
    "  margin-bottom:var(--space-2);\n"
    "}\n"
    ".input-wrapper{\n"
    "  position:relative;\n"
    "}\n"
    ".input-wrapper input{\n"
    "  width:100%;\n"
    "  padding:var(--space-3) var(--space-4);\n"
    "  background:var(--bg-input);\n"
    "  border:1px solid var(--border-color);\n"
    "  border-radius:var(--radius-md);\n"
    "  color:var(--text-primary);\n"
    "  font-size:var(--text-base);\n"
    "  font-family:var(--font-sans);\n"
    "  outline:none;\n"
    "  transition:border-color .2s,box-shadow .2s;\n"
    "}\n"
    ".input-wrapper input::placeholder{\n"
    "  color:var(--text-muted);\n"
    "}\n"
    ".input-wrapper input:focus{\n"
    "  border-color:var(--border-focus);\n"
    "  box-shadow:0 0 0 3px rgba(91,106,191,.2);\n"
    "}\n"
    ".input-wrapper input.input-error{\n"
    "  border-color:var(--error);\n"
    "  box-shadow:0 0 0 3px rgba(239,95,95,.15);\n"
    "}\n"
    ".btn{\n"
    "  display:inline-flex;\n"
    "  align-items:center;\n"
    "  justify-content:center;\n"
    "  width:100%;\n"
    "  padding:var(--space-3) var(--space-4);\n"
    "  border:none;\n"
    "  border-radius:var(--radius-md);\n"
    "  font-size:var(--text-base);\n"
    "  font-weight:600;\n"
    "  font-family:var(--font-sans);\n"
    "  cursor:pointer;\n"
    "  transition:background .2s,transform .1s,opacity .2s;\n"
    "  outline:none;\n"
    "}\n"
    ".btn:active{transform:scale(.98)}\n"
    ".btn-primary{\n"
    "  background:var(--accent);\n"
    "  color:#fff;\n"
    "}\n"
    ".btn-primary:hover{background:var(--accent-hover)}\n"
    ".btn-primary:active{background:var(--accent-active)}\n"
    ".btn-primary:disabled{\n"
    "  opacity:.55;\n"
    "  cursor:not-allowed;\n"
    "  transform:none;\n"
    "}\n"
    ".btn-secondary{\n"
    "  background:var(--bg-tertiary);\n"
    "  color:var(--text-secondary);\n"
    "  border:1px solid var(--border-color);\n"
    "}\n"
    ".btn-secondary:hover{\n"
    "  background:var(--bg-input);\n"
    "  color:var(--text-primary);\n"
    "}\n"
    ".btn-copy{\n"
    "  background:var(--bg-tertiary);\n"
    "  color:var(--text-secondary);\n"
    "  border:1px solid var(--border-color);\n"
    "  padding:var(--space-2) var(--space-4);\n"
    "  font-size:var(--text-sm);\n"
    "  width:auto;\n"
    "}\n"
    ".btn-copy:hover{\n"
    "  background:var(--bg-input);\n"
    "  color:var(--text-primary);\n"
    "}\n"
    ".btn-copy.copied{\n"
    "  background:var(--success-bg);\n"
    "  color:var(--success);\n"
    "  border-color:var(--success);\n"
    "}\n"
    ".error-msg{\n"
    "  background:var(--error-bg);\n"
    "  color:var(--error);\n"
    "  border:1px solid rgba(239,95,95,.25);\n"
    "  border-radius:var(--radius-sm);\n"
    "  padding:var(--space-3) var(--space-4);\n"
    "  font-size:var(--text-sm);\n"
    "  margin-bottom:var(--space-5);\n"
    "  display:none;\n"
    "}\n"
    ".error-msg.visible{display:block}\n"
    ".success-section{\n"
    "  display:none;\n"
    "}\n"
    ".success-section.visible{display:block}\n"
    ".token-section{\n"
    "  margin-bottom:var(--space-5);\n"
    "}\n"
    ".token-section label{\n"
    "  display:block;\n"
    "  font-size:var(--text-sm);\n"
    "  font-weight:500;\n"
    "  color:var(--text-secondary);\n"
    "  margin-bottom:var(--space-2);\n"
    "}\n"
    ".token-area{\n"
    "  width:100%;\n"
    "  min-height:80px;\n"
    "  background:var(--bg-input);\n"
    "  border:1px solid var(--border-color);\n"
    "  border-radius:var(--radius-md);\n"
    "  color:var(--text-primary);\n"
    "  font-family:var(--font-mono);\n"
    "  font-size:var(--text-xs);\n"
    "  padding:var(--space-3);\n"
    "  resize:vertical;\n"
    "  outline:none;\n"
    "  word-break:break-all;\n"
    "}\n"
    ".token-actions{\n"
    "  display:flex;\n"
    "  justify-content:flex-end;\n"
    "  margin-top:var(--space-2);\n"
    "}\n"
    ".user-info{\n"
    "  background:var(--bg-tertiary);\n"
    "  border:1px solid var(--border-color);\n"
    "  border-radius:var(--radius-md);\n"
    "  padding:var(--space-4);\n"
    "}\n"
    ".user-info h3{\n"
    "  font-size:var(--text-sm);\n"
    "  font-weight:600;\n"
    "  color:var(--text-secondary);\n"
    "  margin-bottom:var(--space-3);\n"
    "  text-transform:uppercase;\n"
    "  letter-spacing:.05em;\n"
    "}\n"
    ".user-info-row{\n"
    "  display:flex;\n"
    "  justify-content:space-between;\n"
    "  align-items:center;\n"
    "  padding:var(--space-2) 0;\n"
    "  border-bottom:1px solid var(--border-color);\n"
    "}\n"
    ".user-info-row:last-child{border-bottom:none}\n"
    ".user-info-row .label{\n"
    "  font-size:var(--text-sm);\n"
    "  color:var(--text-muted);\n"
    "}\n"
    ".user-info-row .value{\n"
    "  font-size:var(--text-sm);\n"
    "  color:var(--text-primary);\n"
    "  font-weight:500;\n"
    "}\n"
    ".switch-link{\n"
    "  text-align:center;\n"
    "  margin-top:var(--space-5);\n"
    "  font-size:var(--text-sm);\n"
    "  color:var(--text-muted);\n"
    "}\n"
    ".switch-link a{\n"
    "  color:var(--accent);\n"
    "  text-decoration:none;\n"
    "  cursor:pointer;\n"
    "  font-weight:500;\n"
    "}\n"
    ".switch-link a:hover{\n"
    "  text-decoration:underline;\n"
    "}\n"
    ".spinner{\n"
    "  display:inline-block;\n"
    "  width:16px;\n"
    "  height:16px;\n"
    "  border:2px solid rgba(255,255,255,.3);\n"
    "  border-top-color:#fff;\n"
    "  border-radius:50%;\n"
    "  animation:spin .6s linear infinite;\n"
    "  margin-right:var(--space-2);\n"
    "  vertical-align:middle;\n"
    "}\n"
    "@keyframes spin{to{transform:rotate(360deg)}}\n"
    ".form-section{display:none}\n"
    ".form-section.visible{display:block}\n"
    ".logout-section{\n"
    "  margin-top:var(--space-5);\n"
    "  text-align:center;\n"
    "}\n"
    ".field-error{\n"
    "  font-size:var(--text-xs);\n"
    "  color:var(--error);\n"
    "  margin-top:var(--space-1);\n"
    "  display:none;\n"
    "}\n"
    ".field-error.visible{display:block}\n"
    "@media(max-width:480px){\n"
    "  .card{padding:var(--space-6)}\n"
    "  .header h1{font-size:var(--text-xl)}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"bg-orb\"></div>\n"
    "<div class=\"bg-orb\"></div>\n"
    "<div class=\"bg-orb\"></div>\n"
    "<div class=\"container\">\n"
    "  <div class=\"card\">\n"
    "    <!-- Login Form -->\n"
    "    <div id=\"loginSection\" class=\"form-section visible\">\n"
    "      <div class=\"header\">\n"
    "        <h1>SSO 统一认证</h1>\n"
    "        <p>请登录您的账号</p>\n"
    "      </div>\n"
    "      <div id=\"loginError\" class=\"error-msg\"></div>\n"
    "      <form id=\"loginForm\" novalidate>\n"
    "        <div class=\"form-group\">\n"
    "          <label for=\"loginUsername\">用户名</label>\n"
    "          <div class=\"input-wrapper\">\n"
    "            <input type=\"text\" id=\"loginUsername\" name=\"username\" placeholder=\"请输入用户名\" autocomplete=\"username\" required>\n"
    "          </div>\n"
    "          <div id=\"loginUsernameError\" class=\"field-error\">请输入用户名</div>\n"
    "        </div>\n"
    "        <div class=\"form-group\">\n"
    "          <label for=\"loginPassword\">密码</label>\n"
    "          <div class=\"input-wrapper\">\n"
    "            <input type=\"password\" id=\"loginPassword\" name=\"password\" placeholder=\"请输入密码\" autocomplete=\"current-password\" required>\n"
    "          </div>\n"
    "          <div id=\"loginPasswordError\" class=\"field-error\">请输入密码</div>\n"
    "        </div>\n"
    "        <button type=\"submit\" id=\"loginBtn\" class=\"btn btn-primary\">登录</button>\n"
    "      </form>\n"
    "      <div class=\"switch-link\">\n"
    "        还没有账号？<a id=\"showRegister\">立即注册</a>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- Register Form -->\n"
    "    <div id=\"registerSection\" class=\"form-section\">\n"
    "      <div class=\"header\">\n"
    "        <h1>注册账号</h1>\n"
    "        <p>创建新的 SSO 账号</p>\n"
    "      </div>\n"
    "      <div id=\"registerError\" class=\"error-msg\"></div>\n"
    "      <form id=\"registerForm\" novalidate>\n"
    "        <div class=\"form-group\">\n"
    "          <label for=\"regUsername\">用户名</label>\n"
    "          <div class=\"input-wrapper\">\n"
    "            <input type=\"text\" id=\"regUsername\" name=\"username\" placeholder=\"请输入用户名\" autocomplete=\"username\" required>\n"
    "          </div>\n"
    "          <div id=\"regUsernameError\" class=\"field-error\">请输入用户名</div>\n"
    "        </div>\n"
    "        <div class=\"form-group\">\n"
    "          <label for=\"regDisplayName\">显示名称</label>\n"
    "          <div class=\"input-wrapper\">\n"
    "            <input type=\"text\" id=\"regDisplayName\" name=\"display_name\" placeholder=\"请输入显示名称\" required>\n"
    "          </div>\n"
    "          <div id=\"regDisplayNameError\" class=\"field-error\">请输入显示名称</div>\n"
    "        </div>\n"
    "        <div class=\"form-group\">\n"
    "          <label for=\"regPassword\">密码</label>\n"
    "          <div class=\"input-wrapper\">\n"
    "            <input type=\"password\" id=\"regPassword\" name=\"password\" placeholder=\"请输入密码\" autocomplete=\"new-password\" required>\n"
    "          </div>\n"
    "          <div id=\"regPasswordError\" class=\"field-error\">请输入密码</div>\n"
    "        </div>\n"
    "        <button type=\"submit\" id=\"registerBtn\" class=\"btn btn-primary\">注册</button>\n"
    "      </form>\n"
    "      <div class=\"switch-link\">\n"
    "        已有账号？<a id=\"showLogin\">返回登录</a>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- Success Section -->\n"
    "    <div id=\"successSection\" class=\"success-section\">\n"
    "      <div class=\"header\">\n"
    "        <h1>登录成功</h1>\n"
    "        <p>认证令牌已生成</p>\n"
    "      </div>\n"
    "      <div class=\"token-section\">\n"
    "        <label>认证令牌 (Token)</label>\n"
    "        <textarea id=\"tokenArea\" class=\"token-area\" readonly></textarea>\n"
    "        <div class=\"token-actions\">\n"
    "          <button id=\"copyBtn\" class=\"btn btn-copy\">复制令牌</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"user-info\">\n"
    "        <h3>用户信息</h3>\n"
    "        <div class=\"user-info-row\">\n"
    "          <span class=\"label\">用户 ID</span>\n"
    "          <span id=\"infoUserId\" class=\"value\"></span>\n"
    "        </div>\n"
    "        <div class=\"user-info-row\">\n"
    "          <span class=\"label\">用户名</span>\n"
    "          <span id=\"infoUsername\" class=\"value\"></span>\n"
    "        </div>\n"
    "        <div class=\"user-info-row\">\n"
    "          <span class=\"label\">显示名称</span>\n"
    "          <span id=\"infoDisplayName\" class=\"value\"></span>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"logout-section\">\n"
    "        <button id=\"logoutBtn\" class=\"btn btn-secondary\">退出登录</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "(function() {\n"
    "  'use strict';\n"
    "\n"
    "  var loginSection = document.getElementById('loginSection');\n"
    "  var registerSection = document.getElementById('registerSection');\n"
    "  var successSection = document.getElementById('successSection');\n"
    "\n"
    "  var loginForm = document.getElementById('loginForm');\n"
    "  var registerForm = document.getElementById('registerForm');\n"
    "\n"
    "  var loginError = document.getElementById('loginError');\n"
    "  var registerError = document.getElementById('registerError');\n"
    "\n"
    "  var loginUsername = document.getElementById('loginUsername');\n"
    "  var loginPassword = document.getElementById('loginPassword');\n"
    "  var loginBtn = document.getElementById('loginBtn');\n"
    "\n"
    "  var regUsername = document.getElementById('regUsername');\n"
    "  var regDisplayName = document.getElementById('regDisplayName');\n"
    "  var regPassword = document.getElementById('regPassword');\n"
    "  var registerBtn = document.getElementById('registerBtn');\n"
    "\n"
    "  var tokenArea = document.getElementById('tokenArea');\n"
    "  var copyBtn = document.getElementById('copyBtn');\n"
    "  var logoutBtn = document.getElementById('logoutBtn');\n"
    "\n"
    "  var infoUserId = document.getElementById('infoUserId');\n"
    "  var infoUsername = document.getElementById('infoUsername');\n"
    "  var infoDisplayName = document.getElementById('infoDisplayName');\n"
    "\n"
    "  var showRegisterLink = document.getElementById('showRegister');\n"
    "  var showLoginLink = document.getElementById('showLogin');\n"
    "\n"
    "  function showSection(section) {\n"
    "    loginSection.classList.remove('visible');\n"
    "    registerSection.classList.remove('visible');\n"
    "    successSection.classList.remove('visible');\n"
    "    section.classList.add('visible');\n"
    "  }\n"
    "\n"
    "  function clearErrors() {\n"
    "    loginError.classList.remove('visible');\n"
    "    loginError.textContent = '';\n"
    "    registerError.classList.remove('visible');\n"
    "    registerError.textContent = '';\n"
    "    var fieldErrors = document.querySelectorAll('.field-error');\n"
    "    for (var i = 0; i < fieldErrors.length; i++) {\n"
    "      fieldErrors[i].classList.remove('visible');\n"
    "    }\n"
    "    var errorInputs = document.querySelectorAll('.input-error');\n"
    "    for (var j = 0; j < errorInputs.length; j++) {\n"
    "      errorInputs[j].classList.remove('input-error');\n"
    "    }\n"
    "  }\n"
    "\n"
    "  function showFieldError(inputEl, errorEl) {\n"
    "    inputEl.classList.add('input-error');\n"
    "    errorEl.classList.add('visible');\n"
    "  }\n"
    "\n"
    "  function setLoading(btn, loading) {\n"
    "    if (loading) {\n"
    "      btn.disabled = true;\n"
    "      btn.dataset.originalText = btn.textContent;\n"
    "      btn.innerHTML = '<span class=\"spinner\"></span>处理中...';\n"
    "    } else {\n"
    "      btn.disabled = false;\n"
    "      btn.innerHTML = btn.dataset.originalText || btn.textContent;\n"
    "    }\n"
    "  }\n"
    "\n"
    "  function showLoginError(msg) {\n"
    "    loginError.textContent = msg;\n"
    "    loginError.classList.add('visible');\n"
    "  }\n"
    "\n"
    "  function showRegisterError(msg) {\n"
    "    registerError.textContent = msg;\n"
    "    registerError.classList.add('visible');\n"
    "  }\n"
    "\n"
    "  function validateLoginForm() {\n"
    "    var valid = true;\n"
    "    if (!loginUsername.value.trim()) {\n"
    "      showFieldError(loginUsername, document.getElementById('loginUsernameError'));\n"
    "      valid = false;\n"
    "    }\n"
    "    if (!loginPassword.value.trim()) {\n"
    "      showFieldError(loginPassword, document.getElementById('loginPasswordError'));\n"
    "      valid = false;\n"
    "    }\n"
    "    return valid;\n"
    "  }\n"
    "\n"
    "  function validateRegisterForm() {\n"
    "    var valid = true;\n"
    "    if (!regUsername.value.trim()) {\n"
    "      showFieldError(regUsername, document.getElementById('regUsernameError'));\n"
    "      valid = false;\n"
    "    }\n"
    "    if (!regDisplayName.value.trim()) {\n"
    "      showFieldError(regDisplayName, document.getElementById('regDisplayNameError'));\n"
    "      valid = false;\n"
    "    }\n"
    "    if (!regPassword.value.trim()) {\n"
    "      showFieldError(regPassword, document.getElementById('regPasswordError'));\n"
    "      valid = false;\n"
    "    }\n"
    "    return valid;\n"
    "  }\n"
    "\n"
    "  loginForm.addEventListener('submit', function(e) {\n"
    "    e.preventDefault();\n"
    "    clearErrors();\n"
    "    if (!validateLoginForm()) return;\n"
    "\n"
    "    setLoading(loginBtn, true);\n"
    "\n"
    "    fetch('/api/v1/auth/login', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify({\n"
    "        username: loginUsername.value.trim(),\n"
    "        password: loginPassword.value\n"
    "      })\n"
    "    })\n"
    "    .then(function(response) {\n"
    "      return response.json().then(function(data) {\n"
    "        if (!response.ok) {\n"
    "          throw new Error(data.error || '登录失败');\n"
    "        }\n"
    "        return data;\n"
    "      });\n"
    "    })\n"
    "    .then(function(data) {\n"
    "      tokenArea.value = data.token || '';\n"
    "      infoUserId.textContent = data.user_id != null ? data.user_id : '-';\n"
    "      infoUsername.textContent = data.username || '-';\n"
    "      infoDisplayName.textContent = data.display_name || '-';\n"
    "      showSection(successSection);\n"
    "    })\n"
    "    .catch(function(err) {\n"
    "      showLoginError(err.message || '网络错误，请稍后重试');\n"
    "    })\n"
    "    .finally(function() {\n"
    "      setLoading(loginBtn, false);\n"
    "    });\n"
    "  });\n"
    "\n"
    "  registerForm.addEventListener('submit', function(e) {\n"
    "    e.preventDefault();\n"
    "    clearErrors();\n"
    "    if (!validateRegisterForm()) return;\n"
    "\n"
    "    setLoading(registerBtn, true);\n"
    "\n"
    "    fetch('/api/v1/auth/register', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify({\n"
    "        username: regUsername.value.trim(),\n"
    "        password: regPassword.value,\n"
    "        display_name: regDisplayName.value.trim()\n"
    "      })\n"
    "    })\n"
    "    .then(function(response) {\n"
    "      return response.json().then(function(data) {\n"
    "        if (!response.ok) {\n"
    "          throw new Error(data.error || '注册失败');\n"
    "        }\n"
    "        return data;\n"
    "      });\n"
    "    })\n"
    "    .then(function(data) {\n"
    "      loginUsername.value = regUsername.value.trim();\n"
    "      loginPassword.value = '';\n"
    "      clearErrors();\n"
    "      showSection(loginSection);\n"
    "      showLoginError('');\n"
    "      loginError.classList.remove('visible');\n"
    "      loginError.textContent = '';\n"
    "      loginUsername.focus();\n"
    "    })\n"
    "    .catch(function(err) {\n"
    "      showRegisterError(err.message || '网络错误，请稍后重试');\n"
    "    })\n"
    "    .finally(function() {\n"
    "      setLoading(registerBtn, false);\n"
    "    });\n"
    "  });\n"
    "\n"
    "  showRegisterLink.addEventListener('click', function(e) {\n"
    "    e.preventDefault();\n"
    "    clearErrors();\n"
    "    showSection(registerSection);\n"
    "    regUsername.focus();\n"
    "  });\n"
    "\n"
    "  showLoginLink.addEventListener('click', function(e) {\n"
    "    e.preventDefault();\n"
    "    clearErrors();\n"
    "    showSection(loginSection);\n"
    "    loginUsername.focus();\n"
    "  });\n"
    "\n"
    "  copyBtn.addEventListener('click', function() {\n"
    "    if (!tokenArea.value) return;\n"
    "    if (navigator.clipboard && navigator.clipboard.writeText) {\n"
    "      navigator.clipboard.writeText(tokenArea.value).then(function() {\n"
    "        copyBtn.textContent = '已复制';\n"
    "        copyBtn.classList.add('copied');\n"
    "        setTimeout(function() {\n"
    "          copyBtn.textContent = '复制令牌';\n"
    "          copyBtn.classList.remove('copied');\n"
    "        }, 2000);\n"
    "      });\n"
    "    } else {\n"
    "      tokenArea.select();\n"
    "      try {\n"
    "        document.execCommand('copy');\n"
    "        copyBtn.textContent = '已复制';\n"
    "        copyBtn.classList.add('copied');\n"
    "        setTimeout(function() {\n"
    "          copyBtn.textContent = '复制令牌';\n"
    "          copyBtn.classList.remove('copied');\n"
    "        }, 2000);\n"
    "      } catch (ex) {\n"
    "        // fallback: keep selected for manual copy\n"
    "      }\n"
    "    }\n"
    "  });\n"
    "\n"
    "  logoutBtn.addEventListener('click', function() {\n"
    "    tokenArea.value = '';\n"
    "    infoUserId.textContent = '';\n"
    "    infoUsername.textContent = '';\n"
    "    infoDisplayName.textContent = '';\n"
    "    loginUsername.value = '';\n"
    "    loginPassword.value = '';\n"
    "    clearErrors();\n"
    "    showSection(loginSection);\n"
    "  });\n"
    "\n"
    "  // Clear field error on input\n"
    "  var allInputs = document.querySelectorAll('input');\n"
    "  for (var k = 0; k < allInputs.length; k++) {\n"
    "    allInputs[k].addEventListener('input', function() {\n"
    "      this.classList.remove('input-error');\n"
    "      var sibling = this.parentElement.nextElementSibling;\n"
    "      if (sibling && sibling.classList.contains('field-error')) {\n"
    "        sibling.classList.remove('visible');\n"
    "      }\n"
    "    });\n"
    "  }\n"
    "})();\n"
    "</script>\n"
    "</body>\n"
    "</html>"
    ;

#endif /* SSO_LOGIN_PAGE_H */
